RIL_VERSION = 12
# ERRNO
ERRNO_SUCCESS = 0x0000
ERRNO_RADIO_NOT_AVAILABLE = 0x0001
ERRNO_GENERIC_FAILURE = 0x0002
ERRNO_PASSWORD_INCORRECT = 0x0003
ERRNO_SIM_PIN2 = 0x0004
ERRNO_SIM_PUK2 = 0x0005
ERRNO_REQUEST_NOT_SUPPORTED = 0x0006
ERRNO_CANCELLED = 0x0007
ERRNO_OP_NOT_ALLOWED_DURING_VOICE_CALL = 0x0008
ERRNO_OP_NOT_ALLOWED_BEFORE_REG_TO_NW = 0x0009
ERRNO_SMS_SEND_FAIL_RETRY = 0x000a
ERRNO_SIM_ABSENT = 0x000b
ERRNO_SUBSCRIPTION_NOT_AVAILABLE = 0x000c
ERRNO_MODE_NOT_SUPPORTED = 0x000d
ERRNO_FDN_CHECK_FAILURE = 0x000e
ERRNO_ILLEGAL_SIM_OR_ME = 0x000f
ERRNO_MISSING_RESOURCE = 0x0010
ERRNO_NO_SUCH_ELEMENT = 0x0011
ERRNO_DIAL_MODIFIED_TO_USSD = 0x0012
ERRNO_DIAL_MODIFIED_TO_SS = 0x0013
ERRNO_DIAL_MODIFIED_TO_DIAL = 0x0014
ERRNO_USSD_MODIFIED_TO_DIAL = 0x0015
ERRNO_USSD_MODIFIED_TO_SS = 0x0016
ERRNO_USSD_MODIFIED_TO_USSD = 0x0017
ERRNO_SS_MODIFIED_TO_DIAL = 0x0018
ERRNO_SS_MODIFIED_TO_USSD = 0x0019
ERRNO_SUBSCRIPTION_NOT_SUPPORTED = 0x001a
ERRNO_SS_MODIFIED_TO_SS = 0x001b
ERRNO_LCE_NOT_SUPPORTED = 0x0024
ERRNO_NO_MEMORY = 0x0025
ERRNO_INTERNAL_ERR = 0x0026
ERRNO_SYSTEM_ERR = 0x0027
ERRNO_MODEM_ERR = 0x0028
ERRNO_INVALID_STATE = 0x0029
ERRNO_NO_RESOURCES = 0x002a
ERRNO_SIM_ERR = 0x002b
ERRNO_INVALID_ARGUMENTS = 0x002c
ERRNO_INVALID_SIM_STATE = 0x002d
ERRNO_INVALID_MODEM_STATE = 0x002e
ERRNO_INVALID_CALL_ID = 0x002f
ERRNO_NO_SMS_TO_ACK = 0x0030
ERRNO_NETWORK_ERR = 0x0031
ERRNO_REQUEST_RATE_LIMITED = 0x0032
ERRNO_SIM_BUSY = 0x0033
ERRNO_SIM_FULL = 0x0034
ERRNO_NETWORK_REJECT = 0x0035
ERRNO_OPERATION_NOT_ALLOWED = 0x0036
ERRNO_EMPTY_RECORD = 0x0037
ERRNO_INVALID_SMS_FORMAT = 0x0038
ERRNO_ENCODING_ERR = 0x0039
ERRNO_INVALID_SMSC_ADDRESS = 0x003a
ERRNO_NO_SUCH_ENTRY = 0x003b
ERRNO_NETWORK_NOT_READY = 0x003c
ERRNO_NOT_PROVISIONED = 0x003d
ERRNO_NO_SUBSCRIPTION = 0x003e
ERRNO_NO_NETWORK_FOUND = 0x003f
ERRNO_DEVICE_IN_USE = 0x0040
ERRNO_ABORTED = 0x0041
ERRNO_OEM_ERROR_1 = 0x01f5
ERRNO_OEM_ERROR_2 = 0x01f6
ERRNO_OEM_ERROR_3 = 0x01f7
ERRNO_OEM_ERROR_4 = 0x01f8
ERRNO_OEM_ERROR_5 = 0x01f9
ERRNO_OEM_ERROR_6 = 0x01fa
ERRNO_OEM_ERROR_7 = 0x01fb
ERRNO_OEM_ERROR_8 = 0x01fc
ERRNO_OEM_ERROR_9 = 0x01fd
ERRNO_OEM_ERROR_10 = 0x01fe
ERRNO_OEM_ERROR_11 = 0x01ff
ERRNO_OEM_ERROR_12 = 0x0200
ERRNO_OEM_ERROR_13 = 0x0201
ERRNO_OEM_ERROR_14 = 0x0202
ERRNO_OEM_ERROR_15 = 0x0203
ERRNO_OEM_ERROR_16 = 0x0204
ERRNO_OEM_ERROR_17 = 0x0205
ERRNO_OEM_ERROR_18 = 0x0206
ERRNO_OEM_ERROR_19 = 0x0207
ERRNO_OEM_ERROR_20 = 0x0208
ERRNO_OEM_ERROR_21 = 0x0209
ERRNO_OEM_ERROR_22 = 0x020a
ERRNO_OEM_ERROR_23 = 0x020b
ERRNO_OEM_ERROR_24 = 0x020c
ERRNO_OEM_ERROR_25 = 0x020d
ERRNO = {
    ERRNO_SUCCESS: 'SUCCESS',
    ERRNO_RADIO_NOT_AVAILABLE: 'RADIO_NOT_AVAILABLE',
    ERRNO_GENERIC_FAILURE: 'GENERIC_FAILURE',
    ERRNO_PASSWORD_INCORRECT: 'PASSWORD_INCORRECT',
    ERRNO_SIM_PIN2: 'SIM_PIN2',
    ERRNO_SIM_PUK2: 'SIM_PUK2',
    ERRNO_REQUEST_NOT_SUPPORTED: 'REQUEST_NOT_SUPPORTED',
    ERRNO_CANCELLED: 'CANCELLED',
    ERRNO_OP_NOT_ALLOWED_DURING_VOICE_CALL: 'OP_NOT_ALLOWED_DURING_VOICE_CALL',
    ERRNO_OP_NOT_ALLOWED_BEFORE_REG_TO_NW: 'OP_NOT_ALLOWED_BEFORE_REG_TO_NW',
    ERRNO_SMS_SEND_FAIL_RETRY: 'SMS_SEND_FAIL_RETRY',
    ERRNO_SIM_ABSENT: 'SIM_ABSENT',
    ERRNO_SUBSCRIPTION_NOT_AVAILABLE: 'SUBSCRIPTION_NOT_AVAILABLE',
    ERRNO_MODE_NOT_SUPPORTED: 'MODE_NOT_SUPPORTED',
    ERRNO_FDN_CHECK_FAILURE: 'FDN_CHECK_FAILURE',
    ERRNO_ILLEGAL_SIM_OR_ME: 'ILLEGAL_SIM_OR_ME',
    ERRNO_MISSING_RESOURCE: 'MISSING_RESOURCE',
    ERRNO_NO_SUCH_ELEMENT: 'NO_SUCH_ELEMENT',
    ERRNO_DIAL_MODIFIED_TO_USSD: 'DIAL_MODIFIED_TO_USSD',
    ERRNO_DIAL_MODIFIED_TO_SS: 'DIAL_MODIFIED_TO_SS',
    ERRNO_DIAL_MODIFIED_TO_DIAL: 'DIAL_MODIFIED_TO_DIAL',
    ERRNO_USSD_MODIFIED_TO_DIAL: 'USSD_MODIFIED_TO_DIAL',
    ERRNO_USSD_MODIFIED_TO_SS: 'USSD_MODIFIED_TO_SS',
    ERRNO_USSD_MODIFIED_TO_USSD: 'USSD_MODIFIED_TO_USSD',
    ERRNO_SS_MODIFIED_TO_DIAL: 'SS_MODIFIED_TO_DIAL',
    ERRNO_SS_MODIFIED_TO_USSD: 'SS_MODIFIED_TO_USSD',
    ERRNO_SUBSCRIPTION_NOT_SUPPORTED: 'SUBSCRIPTION_NOT_SUPPORTED',
    ERRNO_SS_MODIFIED_TO_SS: 'SS_MODIFIED_TO_SS',
    ERRNO_LCE_NOT_SUPPORTED: 'LCE_NOT_SUPPORTED',
    ERRNO_NO_MEMORY: 'NO_MEMORY',
    ERRNO_INTERNAL_ERR: 'INTERNAL_ERR',
    ERRNO_SYSTEM_ERR: 'SYSTEM_ERR',
    ERRNO_MODEM_ERR: 'MODEM_ERR',
    ERRNO_INVALID_STATE: 'INVALID_STATE',
    ERRNO_NO_RESOURCES: 'NO_RESOURCES',
    ERRNO_SIM_ERR: 'SIM_ERR',
    ERRNO_INVALID_ARGUMENTS: 'INVALID_ARGUMENTS',
    ERRNO_INVALID_SIM_STATE: 'INVALID_SIM_STATE',
    ERRNO_INVALID_MODEM_STATE: 'INVALID_MODEM_STATE',
    ERRNO_INVALID_CALL_ID: 'INVALID_CALL_ID',
    ERRNO_NO_SMS_TO_ACK: 'NO_SMS_TO_ACK',
    ERRNO_NETWORK_ERR: 'NETWORK_ERR',
    ERRNO_REQUEST_RATE_LIMITED: 'REQUEST_RATE_LIMITED',
    ERRNO_SIM_BUSY: 'SIM_BUSY',
    ERRNO_SIM_FULL: 'SIM_FULL',
    ERRNO_NETWORK_REJECT: 'NETWORK_REJECT',
    ERRNO_OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
    ERRNO_EMPTY_RECORD: 'EMPTY_RECORD',
    ERRNO_INVALID_SMS_FORMAT: 'INVALID_SMS_FORMAT',
    ERRNO_ENCODING_ERR: 'ENCODING_ERR',
    ERRNO_INVALID_SMSC_ADDRESS: 'INVALID_SMSC_ADDRESS',
    ERRNO_NO_SUCH_ENTRY: 'NO_SUCH_ENTRY',
    ERRNO_NETWORK_NOT_READY: 'NETWORK_NOT_READY',
    ERRNO_NOT_PROVISIONED: 'NOT_PROVISIONED',
    ERRNO_NO_SUBSCRIPTION: 'NO_SUBSCRIPTION',
    ERRNO_NO_NETWORK_FOUND: 'NO_NETWORK_FOUND',
    ERRNO_DEVICE_IN_USE: 'DEVICE_IN_USE',
    ERRNO_ABORTED: 'ABORTED',
    ERRNO_OEM_ERROR_1: 'OEM_ERROR_1',
    ERRNO_OEM_ERROR_2: 'OEM_ERROR_2',
    ERRNO_OEM_ERROR_3: 'OEM_ERROR_3',
    ERRNO_OEM_ERROR_4: 'OEM_ERROR_4',
    ERRNO_OEM_ERROR_5: 'OEM_ERROR_5',
    ERRNO_OEM_ERROR_6: 'OEM_ERROR_6',
    ERRNO_OEM_ERROR_7: 'OEM_ERROR_7',
    ERRNO_OEM_ERROR_8: 'OEM_ERROR_8',
    ERRNO_OEM_ERROR_9: 'OEM_ERROR_9',
    ERRNO_OEM_ERROR_10: 'OEM_ERROR_10',
    ERRNO_OEM_ERROR_11: 'OEM_ERROR_11',
    ERRNO_OEM_ERROR_12: 'OEM_ERROR_12',
    ERRNO_OEM_ERROR_13: 'OEM_ERROR_13',
    ERRNO_OEM_ERROR_14: 'OEM_ERROR_14',
    ERRNO_OEM_ERROR_15: 'OEM_ERROR_15',
    ERRNO_OEM_ERROR_16: 'OEM_ERROR_16',
    ERRNO_OEM_ERROR_17: 'OEM_ERROR_17',
    ERRNO_OEM_ERROR_18: 'OEM_ERROR_18',
    ERRNO_OEM_ERROR_19: 'OEM_ERROR_19',
    ERRNO_OEM_ERROR_20: 'OEM_ERROR_20',
    ERRNO_OEM_ERROR_21: 'OEM_ERROR_21',
    ERRNO_OEM_ERROR_22: 'OEM_ERROR_22',
    ERRNO_OEM_ERROR_23: 'OEM_ERROR_23',
    ERRNO_OEM_ERROR_24: 'OEM_ERROR_24',
    ERRNO_OEM_ERROR_25: 'OEM_ERROR_25'
}
# CALLSTATE
CALLSTATE_ACTIVE = 0x0000
CALLSTATE_HOLDING = 0x0001
CALLSTATE_DIALING = 0x0002
CALLSTATE_ALERTING = 0x0003
CALLSTATE_INCOMING = 0x0004
CALLSTATE_WAITING = 0x0005
CALLSTATE = {
    CALLSTATE_ACTIVE: 'ACTIVE',
    CALLSTATE_HOLDING: 'HOLDING',
    CALLSTATE_DIALING: 'DIALING',
    CALLSTATE_ALERTING: 'ALERTING',
    CALLSTATE_INCOMING: 'INCOMING',
    CALLSTATE_WAITING: 'WAITING'
}
# RADIOSTATE
RADIOSTATE_OFF = 0x0000
RADIOSTATE_UNAVAILABLE = 0x0001
RADIOSTATE_SIM_NOT_READY = 0x0002
RADIOSTATE_SIM_LOCKED_OR_ABSENT = 0x0003
RADIOSTATE_SIM_READY = 0x0004
RADIOSTATE_RUIM_NOT_READY = 0x0005
RADIOSTATE_RUIM_READY = 0x0006
RADIOSTATE_RUIM_LOCKED_OR_ABSENT = 0x0007
RADIOSTATE_NV_NOT_READY = 0x0008
RADIOSTATE_NV_READY = 0x0009
RADIOSTATE_ON = 0x000a
RADIOSTATE = {
    RADIOSTATE_OFF: 'OFF',
    RADIOSTATE_UNAVAILABLE: 'UNAVAILABLE',
    RADIOSTATE_SIM_NOT_READY: 'SIM_NOT_READY',
    RADIOSTATE_SIM_LOCKED_OR_ABSENT: 'SIM_LOCKED_OR_ABSENT',
    RADIOSTATE_SIM_READY: 'SIM_READY',
    RADIOSTATE_RUIM_NOT_READY: 'RUIM_NOT_READY',
    RADIOSTATE_RUIM_READY: 'RUIM_READY',
    RADIOSTATE_RUIM_LOCKED_OR_ABSENT: 'RUIM_LOCKED_OR_ABSENT',
    RADIOSTATE_NV_NOT_READY: 'NV_NOT_READY',
    RADIOSTATE_NV_READY: 'NV_READY',
    RADIOSTATE_ON: 'ON'
}
# RADIOTECHNOLOGY
RADIOTECHNOLOGY_UNKNOWN = 0x0000
RADIOTECHNOLOGY_GPRS = 0x0001
RADIOTECHNOLOGY_EDGE = 0x0002
RADIOTECHNOLOGY_UMTS = 0x0003
RADIOTECHNOLOGY_IS95A = 0x0004
RADIOTECHNOLOGY_IS95B = 0x0005
RADIOTECHNOLOGY_1xRTT = 0x0006
RADIOTECHNOLOGY_EVDO_0 = 0x0007
RADIOTECHNOLOGY_EVDO_A = 0x0008
RADIOTECHNOLOGY_HSDPA = 0x0009
RADIOTECHNOLOGY_HSUPA = 0x000a
RADIOTECHNOLOGY_HSPA = 0x000b
RADIOTECHNOLOGY_EVDO_B = 0x000c
RADIOTECHNOLOGY_EHRPD = 0x000d
RADIOTECHNOLOGY_LTE = 0x000e
RADIOTECHNOLOGY_HSPAP = 0x000f
RADIOTECHNOLOGY_GSM = 0x0010
RADIOTECHNOLOGY_TD_SCDMA = 0x0011
RADIOTECHNOLOGY_IWLAN = 0x0012
RADIOTECHNOLOGY_LTE_CA = 0x0013
RADIOTECHNOLOGY = {
    RADIOTECHNOLOGY_UNKNOWN: 'UNKNOWN',
    RADIOTECHNOLOGY_GPRS: 'GPRS',
    RADIOTECHNOLOGY_EDGE: 'EDGE',
    RADIOTECHNOLOGY_UMTS: 'UMTS',
    RADIOTECHNOLOGY_IS95A: 'IS95A',
    RADIOTECHNOLOGY_IS95B: 'IS95B',
    RADIOTECHNOLOGY_1xRTT: '1xRTT',
    RADIOTECHNOLOGY_EVDO_0: 'EVDO_0',
    RADIOTECHNOLOGY_EVDO_A: 'EVDO_A',
    RADIOTECHNOLOGY_HSDPA: 'HSDPA',
    RADIOTECHNOLOGY_HSUPA: 'HSUPA',
    RADIOTECHNOLOGY_HSPA: 'HSPA',
    RADIOTECHNOLOGY_EVDO_B: 'EVDO_B',
    RADIOTECHNOLOGY_EHRPD: 'EHRPD',
    RADIOTECHNOLOGY_LTE: 'LTE',
    RADIOTECHNOLOGY_HSPAP: 'HSPAP',
    RADIOTECHNOLOGY_GSM: 'GSM',
    RADIOTECHNOLOGY_TD_SCDMA: 'TD_SCDMA',
    RADIOTECHNOLOGY_IWLAN: 'IWLAN',
    RADIOTECHNOLOGY_LTE_CA: 'LTE_CA'
}
# RADIOACCESSFAMILY
RADIOACCESSFAMILY_UNKNOWN = 0x0001
RADIOACCESSFAMILY_GPRS = 0x0002
RADIOACCESSFAMILY_EDGE = 0x0004
RADIOACCESSFAMILY_UMTS = 0x0008
RADIOACCESSFAMILY_IS95A = 0x0010
RADIOACCESSFAMILY_IS95B = 0x0020
RADIOACCESSFAMILY_1xRTT = 0x0040
RADIOACCESSFAMILY_EVDO_0 = 0x0080
RADIOACCESSFAMILY_EVDO_A = 0x0100
RADIOACCESSFAMILY_HSDPA = 0x0200
RADIOACCESSFAMILY_HSUPA = 0x0400
RADIOACCESSFAMILY_HSPA = 0x0800
RADIOACCESSFAMILY_EVDO_B = 0x1000
RADIOACCESSFAMILY_EHRPD = 0x2000
RADIOACCESSFAMILY_LTE = 0x4000
RADIOACCESSFAMILY_HSPAP = 0x8000
RADIOACCESSFAMILY_GSM = 0x10000
RADIOACCESSFAMILY_TD_SCDMA = 0x20000
RADIOACCESSFAMILY_LTE_CA = 0x80000
RADIOACCESSFAMILY = {
    RADIOACCESSFAMILY_UNKNOWN: 'UNKNOWN',
    RADIOACCESSFAMILY_GPRS: 'GPRS',
    RADIOACCESSFAMILY_EDGE: 'EDGE',
    RADIOACCESSFAMILY_UMTS: 'UMTS',
    RADIOACCESSFAMILY_IS95A: 'IS95A',
    RADIOACCESSFAMILY_IS95B: 'IS95B',
    RADIOACCESSFAMILY_1xRTT: '1xRTT',
    RADIOACCESSFAMILY_EVDO_0: 'EVDO_0',
    RADIOACCESSFAMILY_EVDO_A: 'EVDO_A',
    RADIOACCESSFAMILY_HSDPA: 'HSDPA',
    RADIOACCESSFAMILY_HSUPA: 'HSUPA',
    RADIOACCESSFAMILY_HSPA: 'HSPA',
    RADIOACCESSFAMILY_EVDO_B: 'EVDO_B',
    RADIOACCESSFAMILY_EHRPD: 'EHRPD',
    RADIOACCESSFAMILY_LTE: 'LTE',
    RADIOACCESSFAMILY_HSPAP: 'HSPAP',
    RADIOACCESSFAMILY_GSM: 'GSM',
    RADIOACCESSFAMILY_TD_SCDMA: 'TD_SCDMA',
    RADIOACCESSFAMILY_LTE_CA: 'LTE_CA'
}
# RADIOBANDMODE
RADIOBANDMODE_UNSPECIFIED = 0x0000
RADIOBANDMODE_EURO = 0x0001
RADIOBANDMODE_USA = 0x0002
RADIOBANDMODE_JPN = 0x0003
RADIOBANDMODE_AUS = 0x0004
RADIOBANDMODE_AUS_2 = 0x0005
RADIOBANDMODE_CELL_800 = 0x0006
RADIOBANDMODE_PCS = 0x0007
RADIOBANDMODE_JTACS = 0x0008
RADIOBANDMODE_KOREA_PCS = 0x0009
RADIOBANDMODE_5_450M = 0x000a
RADIOBANDMODE_IMT2000 = 0x000b
RADIOBANDMODE_7_700M_2 = 0x000c
RADIOBANDMODE_8_1800M = 0x000d
RADIOBANDMODE_9_900M = 0x000e
RADIOBANDMODE_10_800M_2 = 0x000f
RADIOBANDMODE_EURO_PAMR_400M = 0x0010
RADIOBANDMODE_AWS = 0x0011
RADIOBANDMODE_USA_2500M = 0x0012
RADIOBANDMODE = {
    RADIOBANDMODE_UNSPECIFIED: 'UNSPECIFIED',
    RADIOBANDMODE_EURO: 'EURO',
    RADIOBANDMODE_USA: 'USA',
    RADIOBANDMODE_JPN: 'JPN',
    RADIOBANDMODE_AUS: 'AUS',
    RADIOBANDMODE_AUS_2: 'AUS_2',
    RADIOBANDMODE_CELL_800: 'CELL_800',
    RADIOBANDMODE_PCS: 'PCS',
    RADIOBANDMODE_JTACS: 'JTACS',
    RADIOBANDMODE_KOREA_PCS: 'KOREA_PCS',
    RADIOBANDMODE_5_450M: '5_450M',
    RADIOBANDMODE_IMT2000: 'IMT2000',
    RADIOBANDMODE_7_700M_2: '7_700M_2',
    RADIOBANDMODE_8_1800M: '8_1800M',
    RADIOBANDMODE_9_900M: '9_900M',
    RADIOBANDMODE_10_800M_2: '10_800M_2',
    RADIOBANDMODE_EURO_PAMR_400M: 'EURO_PAMR_400M',
    RADIOBANDMODE_AWS: 'AWS',
    RADIOBANDMODE_USA_2500M: 'USA_2500M'
}
# RADIOCAPABILITYPHASE
RADIOCAPABILITYPHASE_CONFIGURED = 0x0000
RADIOCAPABILITYPHASE_START = 0x0001
RADIOCAPABILITYPHASE_APPLY = 0x0002
RADIOCAPABILITYPHASE_UNSOL_RSP = 0x0003
RADIOCAPABILITYPHASE_FINISH = 0x0004
RADIOCAPABILITYPHASE = {
    RADIOCAPABILITYPHASE_CONFIGURED: 'CONFIGURED',
    RADIOCAPABILITYPHASE_START: 'START',
    RADIOCAPABILITYPHASE_APPLY: 'APPLY',
    RADIOCAPABILITYPHASE_UNSOL_RSP: 'UNSOL_RSP',
    RADIOCAPABILITYPHASE_FINISH: 'FINISH'
}
# RADIOCAPABILITYSTATUS
RADIOCAPABILITYSTATUS_NONE = 0x0000
RADIOCAPABILITYSTATUS_SUCCESS = 0x0001
RADIOCAPABILITYSTATUS_FAIL = 0x0002
RADIOCAPABILITYSTATUS = {
    RADIOCAPABILITYSTATUS_NONE: 'NONE',
    RADIOCAPABILITYSTATUS_SUCCESS: 'SUCCESS',
    RADIOCAPABILITYSTATUS_FAIL: 'FAIL'
}
# PREFERREDNETWORKTYPE
PREFERREDNETWORKTYPE_GSM_WCDMA = 0x0000
PREFERREDNETWORKTYPE_GSM_ONLY = 0x0001
PREFERREDNETWORKTYPE_WCDMA = 0x0002
PREFERREDNETWORKTYPE_GSM_WCDMA_AUTO = 0x0003
PREFERREDNETWORKTYPE_CDMA_EVDO_AUTO = 0x0004
PREFERREDNETWORKTYPE_CDMA_ONLY = 0x0005
PREFERREDNETWORKTYPE_EVDO_ONLY = 0x0006
PREFERREDNETWORKTYPE_GSM_WCDMA_CDMA_EVDO_AUTO = 0x0007
PREFERREDNETWORKTYPE_LTE_CDMA_EVDO = 0x0008
PREFERREDNETWORKTYPE_LTE_GSM_WCDMA = 0x0009
PREFERREDNETWORKTYPE_LTE_CMDA_EVDO_GSM_WCDMA = 0x000a
PREFERREDNETWORKTYPE_LTE_ONLY = 0x000b
PREFERREDNETWORKTYPE_LTE_WCDMA = 0x000c
PREFERREDNETWORKTYPE = {
    PREFERREDNETWORKTYPE_GSM_WCDMA: 'GSM_WCDMA',
    PREFERREDNETWORKTYPE_GSM_ONLY: 'GSM_ONLY',
    PREFERREDNETWORKTYPE_WCDMA: 'WCDMA',
    PREFERREDNETWORKTYPE_GSM_WCDMA_AUTO: 'GSM_WCDMA_AUTO',
    PREFERREDNETWORKTYPE_CDMA_EVDO_AUTO: 'CDMA_EVDO_AUTO',
    PREFERREDNETWORKTYPE_CDMA_ONLY: 'CDMA_ONLY',
    PREFERREDNETWORKTYPE_EVDO_ONLY: 'EVDO_ONLY',
    PREFERREDNETWORKTYPE_GSM_WCDMA_CDMA_EVDO_AUTO: 'GSM_WCDMA_CDMA_EVDO_AUTO',
    PREFERREDNETWORKTYPE_LTE_CDMA_EVDO: 'LTE_CDMA_EVDO',
    PREFERREDNETWORKTYPE_LTE_GSM_WCDMA: 'LTE_GSM_WCDMA',
    PREFERREDNETWORKTYPE_LTE_CMDA_EVDO_GSM_WCDMA: 'LTE_CMDA_EVDO_GSM_WCDMA',
    PREFERREDNETWORKTYPE_LTE_ONLY: 'LTE_ONLY',
    PREFERREDNETWORKTYPE_LTE_WCDMA: 'LTE_WCDMA'
}
# CDMASUBSCRIPTIONSOURCE
CDMASUBSCRIPTIONSOURCE_RUIM_SIM = 0x0000
CDMASUBSCRIPTIONSOURCE_NV = 0x0001
CDMASUBSCRIPTIONSOURCE = {
    CDMASUBSCRIPTIONSOURCE_RUIM_SIM: 'RUIM_SIM',
    CDMASUBSCRIPTIONSOURCE_NV: 'NV'
}
# UUS_TYPE
UUS_TYPE_TYPE1_IMPLICIT = 0x0000
UUS_TYPE_TYPE1_REQUIRED = 0x0001
UUS_TYPE_TYPE1_NOT_REQUIRED = 0x0002
UUS_TYPE_TYPE2_REQUIRED = 0x0003
UUS_TYPE_TYPE2_NOT_REQUIRED = 0x0004
UUS_TYPE_TYPE3_REQUIRED = 0x0005
UUS_TYPE_TYPE3_NOT_REQUIRED = 0x0006
UUS_TYPE = {
    UUS_TYPE_TYPE1_IMPLICIT: 'TYPE1_IMPLICIT',
    UUS_TYPE_TYPE1_REQUIRED: 'TYPE1_REQUIRED',
    UUS_TYPE_TYPE1_NOT_REQUIRED: 'TYPE1_NOT_REQUIRED',
    UUS_TYPE_TYPE2_REQUIRED: 'TYPE2_REQUIRED',
    UUS_TYPE_TYPE2_NOT_REQUIRED: 'TYPE2_NOT_REQUIRED',
    UUS_TYPE_TYPE3_REQUIRED: 'TYPE3_REQUIRED',
    UUS_TYPE_TYPE3_NOT_REQUIRED: 'TYPE3_NOT_REQUIRED'
}
# UUS_DCS
UUS_DCS_RIL_UUS_DCS_USP = 0x0000
UUS_DCS_RIL_UUS_DCS_OSIHLP = 0x0001
UUS_DCS_RIL_UUS_DCS_X244 = 0x0002
UUS_DCS_RIL_UUS_DCS_RMCF = 0x0003
UUS_DCS_RIL_UUS_DCS_IA5c = 0x0004
UUS_DCS = {
    UUS_DCS_RIL_UUS_DCS_USP: 'RIL_UUS_DCS_USP',
    UUS_DCS_RIL_UUS_DCS_OSIHLP: 'RIL_UUS_DCS_OSIHLP',
    UUS_DCS_RIL_UUS_DCS_X244: 'RIL_UUS_DCS_X244',
    UUS_DCS_RIL_UUS_DCS_RMCF: 'RIL_UUS_DCS_RMCF',
    UUS_DCS_RIL_UUS_DCS_IA5c: 'RIL_UUS_DCS_IA5c'
}
# RADIOTECHNOLOGYFAMILY
RADIOTECHNOLOGYFAMILY_3GPP = 0x0001
RADIOTECHNOLOGYFAMILY_3GPP2 = 0x0002
RADIOTECHNOLOGYFAMILY = {
    RADIOTECHNOLOGYFAMILY_3GPP: '3GPP',
    RADIOTECHNOLOGYFAMILY_3GPP2: '3GPP2'
}
# CARRIERMATCHTYPE
CARRIERMATCHTYPE_ALL = 0x0000
CARRIERMATCHTYPE_SPN = 0x0001
CARRIERMATCHTYPE_IMSI_PREFIX = 0x0002
CARRIERMATCHTYPE_GID1 = 0x0003
CARRIERMATCHTYPE_GID2 = 0x0004
CARRIERMATCHTYPE = {
    CARRIERMATCHTYPE_ALL: 'ALL',
    CARRIERMATCHTYPE_SPN: 'SPN',
    CARRIERMATCHTYPE_IMSI_PREFIX: 'IMSI_PREFIX',
    CARRIERMATCHTYPE_GID1: 'GID1',
    CARRIERMATCHTYPE_GID2: 'GID2'
}
# LASTCALLFAILCAUSE
LASTCALLFAILCAUSE_UNOBTAINABLE_NUMBER = 0x0001
LASTCALLFAILCAUSE_NO_ROUTE_TO_DESTINATION = 0x0003
LASTCALLFAILCAUSE_CHANNEL_UNACCEPTABLE = 0x0006
LASTCALLFAILCAUSE_OPERATOR_DETERMINED_BARRING = 0x0008
LASTCALLFAILCAUSE_NORMAL = 0x0010
LASTCALLFAILCAUSE_BUSY = 0x0011
LASTCALLFAILCAUSE_NO_USER_RESPONDING = 0x0012
LASTCALLFAILCAUSE_NO_ANSWER_FROM_USER = 0x0013
LASTCALLFAILCAUSE_CALL_REJECTED = 0x0015
LASTCALLFAILCAUSE_NUMBER_CHANGED = 0x0016
LASTCALLFAILCAUSE_PREEMPTION = 0x0019
LASTCALLFAILCAUSE_DESTINATION_OUT_OF_ORDER = 0x001b
LASTCALLFAILCAUSE_INVALID_NUMBER_FORMAT = 0x001c
LASTCALLFAILCAUSE_FACILITY_REJECTED = 0x001d
LASTCALLFAILCAUSE_RESP_TO_STATUS_ENQUIRY = 0x001e
LASTCALLFAILCAUSE_NORMAL_UNSPECIFIED = 0x001f
LASTCALLFAILCAUSE_CONGESTION = 0x0022
LASTCALLFAILCAUSE_NETWORK_OUT_OF_ORDER = 0x0026
LASTCALLFAILCAUSE_TEMPORARY_FAILURE = 0x0029
LASTCALLFAILCAUSE_SWITCHING_EQUIPMENT_CONGESTION = 0x002a
LASTCALLFAILCAUSE_ACCESS_INFORMATION_DISCARDED = 0x002b
LASTCALLFAILCAUSE_REQUESTED_CIRCUIT_OR_CHANNEL_NOT_AVAILABLE = 0x002c
LASTCALLFAILCAUSE_RESOURCES_UNAVAILABLE_OR_UNSPECIFIED = 0x002f
LASTCALLFAILCAUSE_QOS_UNAVAILABLE = 0x0031
LASTCALLFAILCAUSE_REQUESTED_FACILITY_NOT_SUBSCRIBED = 0x0032
LASTCALLFAILCAUSE_INCOMING_CALLS_BARRED_WITHIN_CUG = 0x0037
LASTCALLFAILCAUSE_BEARER_CAPABILITY_NOT_AUTHORIZED = 0x0039
LASTCALLFAILCAUSE_BEARER_CAPABILITY_UNAVAILABLE = 0x003a
LASTCALLFAILCAUSE_SERVICE_OPTION_NOT_AVAILABLE = 0x003f
LASTCALLFAILCAUSE_BEARER_SERVICE_NOT_IMPLEMENTED = 0x0041
LASTCALLFAILCAUSE_ACM_LIMIT_EXCEEDED = 0x0044
LASTCALLFAILCAUSE_REQUESTED_FACILITY_NOT_IMPLEMENTED = 0x0045
LASTCALLFAILCAUSE_ONLY_DIGITAL_INFORMATION_BEARER_AVAILABLE = 0x0046
LASTCALLFAILCAUSE_SERVICE_OR_OPTION_NOT_IMPLEMENTED = 0x004f
LASTCALLFAILCAUSE_INVALID_TRANSACTION_IDENTIFIER = 0x0051
LASTCALLFAILCAUSE_USER_NOT_MEMBER_OF_CUG = 0x0057
LASTCALLFAILCAUSE_INCOMPATIBLE_DESTINATION = 0x0058
LASTCALLFAILCAUSE_INVALID_TRANSIT_NW_SELECTION = 0x005b
LASTCALLFAILCAUSE_SEMANTICALLY_INCORRECT_MESSAGE = 0x005f
LASTCALLFAILCAUSE_INVALID_MANDATORY_INFORMATION = 0x0060
LASTCALLFAILCAUSE_MESSAGE_TYPE_NON_IMPLEMENTED = 0x0061
LASTCALLFAILCAUSE_MESSAGE_TYPE_NOT_COMPATIBLE_WITH_PROTOCOL_STATE = 0x0062
LASTCALLFAILCAUSE_INFORMATION_ELEMENT_NON_EXISTENT = 0x0063
LASTCALLFAILCAUSE_CONDITIONAL_IE_ERROR = 0x0064
LASTCALLFAILCAUSE_MESSAGE_NOT_COMPATIBLE_WITH_PROTOCOL_STATE = 0x0065
LASTCALLFAILCAUSE_RECOVERY_ON_TIMER_EXPIRED = 0x0066
LASTCALLFAILCAUSE_PROTOCOL_ERROR_UNSPECIFIED = 0x006f
LASTCALLFAILCAUSE_INTERWORKING_UNSPECIFIED = 0x007f
LASTCALLFAILCAUSE_CALL_BARRED = 0x00f0
LASTCALLFAILCAUSE_FDN_BLOCKED = 0x00f1
LASTCALLFAILCAUSE_IMSI_UNKNOWN_IN_VLR = 0x00f2
LASTCALLFAILCAUSE_IMEI_NOT_ACCEPTED = 0x00f3
LASTCALLFAILCAUSE_DIAL_MODIFIED_TO_USSD = 0x00f4
LASTCALLFAILCAUSE_DIAL_MODIFIED_TO_SS = 0x00f5
LASTCALLFAILCAUSE_DIAL_MODIFIED_TO_DIAL = 0x00f6
LASTCALLFAILCAUSE_CDMA_LOCKED_UNTIL_POWER_CYCLE = 0x03e8
LASTCALLFAILCAUSE_CDMA_DROP = 0x03e9
LASTCALLFAILCAUSE_CDMA_INTERCEPT = 0x03ea
LASTCALLFAILCAUSE_CDMA_REORDER = 0x03eb
LASTCALLFAILCAUSE_CDMA_SO_REJECT = 0x03ec
LASTCALLFAILCAUSE_CDMA_RETRY_ORDER = 0x03ed
LASTCALLFAILCAUSE_CDMA_ACCESS_FAILURE = 0x03ee
LASTCALLFAILCAUSE_CDMA_PREEMPTED = 0x03ef
LASTCALLFAILCAUSE_CDMA_NOT_EMERGENCY = 0x03f0
LASTCALLFAILCAUSE_CDMA_ACCESS_BLOCKED = 0x03f1
LASTCALLFAILCAUSE_ERROR_UNSPECIFIED = 0xffff
LASTCALLFAILCAUSE = {
    LASTCALLFAILCAUSE_UNOBTAINABLE_NUMBER: 'UNOBTAINABLE_NUMBER',
    LASTCALLFAILCAUSE_NO_ROUTE_TO_DESTINATION: 'NO_ROUTE_TO_DESTINATION',
    LASTCALLFAILCAUSE_CHANNEL_UNACCEPTABLE: 'CHANNEL_UNACCEPTABLE',
    LASTCALLFAILCAUSE_OPERATOR_DETERMINED_BARRING: 'OPERATOR_DETERMINED_BARRING',
    LASTCALLFAILCAUSE_NORMAL: 'NORMAL',
    LASTCALLFAILCAUSE_BUSY: 'BUSY',
    LASTCALLFAILCAUSE_NO_USER_RESPONDING: 'NO_USER_RESPONDING',
    LASTCALLFAILCAUSE_NO_ANSWER_FROM_USER: 'NO_ANSWER_FROM_USER',
    LASTCALLFAILCAUSE_CALL_REJECTED: 'CALL_REJECTED',
    LASTCALLFAILCAUSE_NUMBER_CHANGED: 'NUMBER_CHANGED',
    LASTCALLFAILCAUSE_PREEMPTION: 'PREEMPTION',
    LASTCALLFAILCAUSE_DESTINATION_OUT_OF_ORDER: 'DESTINATION_OUT_OF_ORDER',
    LASTCALLFAILCAUSE_INVALID_NUMBER_FORMAT: 'INVALID_NUMBER_FORMAT',
    LASTCALLFAILCAUSE_FACILITY_REJECTED: 'FACILITY_REJECTED',
    LASTCALLFAILCAUSE_RESP_TO_STATUS_ENQUIRY: 'RESP_TO_STATUS_ENQUIRY',
    LASTCALLFAILCAUSE_NORMAL_UNSPECIFIED: 'NORMAL_UNSPECIFIED',
    LASTCALLFAILCAUSE_CONGESTION: 'CONGESTION',
    LASTCALLFAILCAUSE_NETWORK_OUT_OF_ORDER: 'NETWORK_OUT_OF_ORDER',
    LASTCALLFAILCAUSE_TEMPORARY_FAILURE: 'TEMPORARY_FAILURE',
    LASTCALLFAILCAUSE_SWITCHING_EQUIPMENT_CONGESTION: 'SWITCHING_EQUIPMENT_CONGESTION',
    LASTCALLFAILCAUSE_ACCESS_INFORMATION_DISCARDED: 'ACCESS_INFORMATION_DISCARDED',
    LASTCALLFAILCAUSE_REQUESTED_CIRCUIT_OR_CHANNEL_NOT_AVAILABLE: 'REQUESTED_CIRCUIT_OR_CHANNEL_NOT_AVAILABLE',
    LASTCALLFAILCAUSE_RESOURCES_UNAVAILABLE_OR_UNSPECIFIED: 'RESOURCES_UNAVAILABLE_OR_UNSPECIFIED',
    LASTCALLFAILCAUSE_QOS_UNAVAILABLE: 'QOS_UNAVAILABLE',
    LASTCALLFAILCAUSE_REQUESTED_FACILITY_NOT_SUBSCRIBED: 'REQUESTED_FACILITY_NOT_SUBSCRIBED',
    LASTCALLFAILCAUSE_INCOMING_CALLS_BARRED_WITHIN_CUG: 'INCOMING_CALLS_BARRED_WITHIN_CUG',
    LASTCALLFAILCAUSE_BEARER_CAPABILITY_NOT_AUTHORIZED: 'BEARER_CAPABILITY_NOT_AUTHORIZED',
    LASTCALLFAILCAUSE_BEARER_CAPABILITY_UNAVAILABLE: 'BEARER_CAPABILITY_UNAVAILABLE',
    LASTCALLFAILCAUSE_SERVICE_OPTION_NOT_AVAILABLE: 'SERVICE_OPTION_NOT_AVAILABLE',
    LASTCALLFAILCAUSE_BEARER_SERVICE_NOT_IMPLEMENTED: 'BEARER_SERVICE_NOT_IMPLEMENTED',
    LASTCALLFAILCAUSE_ACM_LIMIT_EXCEEDED: 'ACM_LIMIT_EXCEEDED',
    LASTCALLFAILCAUSE_REQUESTED_FACILITY_NOT_IMPLEMENTED: 'REQUESTED_FACILITY_NOT_IMPLEMENTED',
    LASTCALLFAILCAUSE_ONLY_DIGITAL_INFORMATION_BEARER_AVAILABLE: 'ONLY_DIGITAL_INFORMATION_BEARER_AVAILABLE',
    LASTCALLFAILCAUSE_SERVICE_OR_OPTION_NOT_IMPLEMENTED: 'SERVICE_OR_OPTION_NOT_IMPLEMENTED',
    LASTCALLFAILCAUSE_INVALID_TRANSACTION_IDENTIFIER: 'INVALID_TRANSACTION_IDENTIFIER',
    LASTCALLFAILCAUSE_USER_NOT_MEMBER_OF_CUG: 'USER_NOT_MEMBER_OF_CUG',
    LASTCALLFAILCAUSE_INCOMPATIBLE_DESTINATION: 'INCOMPATIBLE_DESTINATION',
    LASTCALLFAILCAUSE_INVALID_TRANSIT_NW_SELECTION: 'INVALID_TRANSIT_NW_SELECTION',
    LASTCALLFAILCAUSE_SEMANTICALLY_INCORRECT_MESSAGE: 'SEMANTICALLY_INCORRECT_MESSAGE',
    LASTCALLFAILCAUSE_INVALID_MANDATORY_INFORMATION: 'INVALID_MANDATORY_INFORMATION',
    LASTCALLFAILCAUSE_MESSAGE_TYPE_NON_IMPLEMENTED: 'MESSAGE_TYPE_NON_IMPLEMENTED',
    LASTCALLFAILCAUSE_MESSAGE_TYPE_NOT_COMPATIBLE_WITH_PROTOCOL_STATE: 'MESSAGE_TYPE_NOT_COMPATIBLE_WITH_PROTOCOL_STATE',
    LASTCALLFAILCAUSE_INFORMATION_ELEMENT_NON_EXISTENT: 'INFORMATION_ELEMENT_NON_EXISTENT',
    LASTCALLFAILCAUSE_CONDITIONAL_IE_ERROR: 'CONDITIONAL_IE_ERROR',
    LASTCALLFAILCAUSE_MESSAGE_NOT_COMPATIBLE_WITH_PROTOCOL_STATE: 'MESSAGE_NOT_COMPATIBLE_WITH_PROTOCOL_STATE',
    LASTCALLFAILCAUSE_RECOVERY_ON_TIMER_EXPIRED: 'RECOVERY_ON_TIMER_EXPIRED',
    LASTCALLFAILCAUSE_PROTOCOL_ERROR_UNSPECIFIED: 'PROTOCOL_ERROR_UNSPECIFIED',
    LASTCALLFAILCAUSE_INTERWORKING_UNSPECIFIED: 'INTERWORKING_UNSPECIFIED',
    LASTCALLFAILCAUSE_CALL_BARRED: 'CALL_BARRED',
    LASTCALLFAILCAUSE_FDN_BLOCKED: 'FDN_BLOCKED',
    LASTCALLFAILCAUSE_IMSI_UNKNOWN_IN_VLR: 'IMSI_UNKNOWN_IN_VLR',
    LASTCALLFAILCAUSE_IMEI_NOT_ACCEPTED: 'IMEI_NOT_ACCEPTED',
    LASTCALLFAILCAUSE_DIAL_MODIFIED_TO_USSD: 'DIAL_MODIFIED_TO_USSD',
    LASTCALLFAILCAUSE_DIAL_MODIFIED_TO_SS: 'DIAL_MODIFIED_TO_SS',
    LASTCALLFAILCAUSE_DIAL_MODIFIED_TO_DIAL: 'DIAL_MODIFIED_TO_DIAL',
    LASTCALLFAILCAUSE_CDMA_LOCKED_UNTIL_POWER_CYCLE: 'CDMA_LOCKED_UNTIL_POWER_CYCLE',
    LASTCALLFAILCAUSE_CDMA_DROP: 'CDMA_DROP',
    LASTCALLFAILCAUSE_CDMA_INTERCEPT: 'CDMA_INTERCEPT',
    LASTCALLFAILCAUSE_CDMA_REORDER: 'CDMA_REORDER',
    LASTCALLFAILCAUSE_CDMA_SO_REJECT: 'CDMA_SO_REJECT',
    LASTCALLFAILCAUSE_CDMA_RETRY_ORDER: 'CDMA_RETRY_ORDER',
    LASTCALLFAILCAUSE_CDMA_ACCESS_FAILURE: 'CDMA_ACCESS_FAILURE',
    LASTCALLFAILCAUSE_CDMA_PREEMPTED: 'CDMA_PREEMPTED',
    LASTCALLFAILCAUSE_CDMA_NOT_EMERGENCY: 'CDMA_NOT_EMERGENCY',
    LASTCALLFAILCAUSE_CDMA_ACCESS_BLOCKED: 'CDMA_ACCESS_BLOCKED',
    LASTCALLFAILCAUSE_ERROR_UNSPECIFIED: 'ERROR_UNSPECIFIED'
}
# DATACALLFAILCAUSE
DATACALLFAILCAUSE_TETHERED_CALL_ACTIVE = -6
DATACALLFAILCAUSE_RADIO_POWER_OFF = -5
DATACALLFAILCAUSE_PREF_RADIO_TECH_CHANGED = -4
DATACALLFAILCAUSE_SIGNAL_LOST = -3
DATACALLFAILCAUSE_DATA_REGISTRATION_FAIL = -2
DATACALLFAILCAUSE_VOICE_REGISTRATION_FAIL = -1
DATACALLFAILCAUSE_NONE = 0x0000
DATACALLFAILCAUSE_OPERATOR_BARRED = 0x0008
DATACALLFAILCAUSE_NAS_SIGNALLING = 0x000e
DATACALLFAILCAUSE_LLC_SNDCP = 0x0019
DATACALLFAILCAUSE_INSUFFICIENT_RESOURCES = 0x001a
DATACALLFAILCAUSE_MISSING_UKNOWN_APN = 0x001b
DATACALLFAILCAUSE_UNKNOWN_PDP_ADDRESS_TYPE = 0x001c
DATACALLFAILCAUSE_USER_AUTHENTICATION = 0x001d
DATACALLFAILCAUSE_ACTIVATION_REJECT_GGSN = 0x001e
DATACALLFAILCAUSE_ACTIVATION_REJECT_UNSPECIFIED = 0x001f
DATACALLFAILCAUSE_SERVICE_OPTION_NOT_SUPPORTED = 0x0020
DATACALLFAILCAUSE_SERVICE_OPTION_NOT_SUBSCRIBED = 0x0021
DATACALLFAILCAUSE_SERVICE_OPTION_OUT_OF_ORDER = 0x0022
DATACALLFAILCAUSE_NSAPI_IN_USE = 0x0023
DATACALLFAILCAUSE_REGULAR_DEACTIVATION = 0x0024
DATACALLFAILCAUSE_QOS_NOT_ACCEPTED = 0x0025
DATACALLFAILCAUSE_NETWORK_FAILURE = 0x0026
DATACALLFAILCAUSE_UMTS_REACTIVATION_REQ = 0x0027
DATACALLFAILCAUSE_FEATURE_NOT_SUPP = 0x0028
DATACALLFAILCAUSE_TFT_SEMANTIC_ERROR = 0x0029
DATACALLFAILCAUSE_TFT_SYTAX_ERROR = 0x002a
DATACALLFAILCAUSE_UNKNOWN_PDP_CONTEXT = 0x002b
DATACALLFAILCAUSE_FILTER_SEMANTIC_ERROR = 0x002c
DATACALLFAILCAUSE_FILTER_SYTAX_ERROR = 0x002d
DATACALLFAILCAUSE_PDP_WITHOUT_ACTIVE_TFT = 0x002e
DATACALLFAILCAUSE_ONLY_IPV4_ALLOWED = 0x0032
DATACALLFAILCAUSE_ONLY_IPV6_ALLOWED = 0x0033
DATACALLFAILCAUSE_ONLY_SINGLE_BEARER_ALLOWED = 0x0034
DATACALLFAILCAUSE_ESM_INFO_NOT_RECEIVED = 0x0035
DATACALLFAILCAUSE_PDN_CONN_DOES_NOT_EXIST = 0x0036
DATACALLFAILCAUSE_MULTI_CONN_TO_SAME_PDN_NOT_ALLOWED = 0x0037
DATACALLFAILCAUSE_MAX_ACTIVE_PDP_CONTEXT_REACHED = 0x0041
DATACALLFAILCAUSE_UNSUPPORTED_APN_IN_CURRENT_PLMN = 0x0042
DATACALLFAILCAUSE_INVALID_TRANSACTION_ID = 0x0051
DATACALLFAILCAUSE_MESSAGE_INCORRECT_SEMANTIC = 0x005f
DATACALLFAILCAUSE_INVALID_MANDATORY_INFO = 0x0060
DATACALLFAILCAUSE_MESSAGE_TYPE_UNSUPPORTED = 0x0061
DATACALLFAILCAUSE_MSG_TYPE_NONCOMPATIBLE_STATE = 0x0062
DATACALLFAILCAUSE_UNKNOWN_INFO_ELEMENT = 0x0063
DATACALLFAILCAUSE_CONDITIONAL_IE_ERROR = 0x0064
DATACALLFAILCAUSE_MSG_AND_PROTOCOL_STATE_UNCOMPATIBLE = 0x0065
DATACALLFAILCAUSE_PROTOCOL_ERRORS = 0x006f
DATACALLFAILCAUSE_APN_TYPE_CONFLICT = 0x0070
DATACALLFAILCAUSE_INVALID_PCSCF_ADDR = 0x0071
DATACALLFAILCAUSE_INTERNAL_CALL_PREEMPT_BY_HIGH_PRIO_APN = 0x0072
DATACALLFAILCAUSE_EMM_ACCESS_BARRED = 0x0073
DATACALLFAILCAUSE_EMERGENCY_IFACE_ONLY = 0x0074
DATACALLFAILCAUSE_IFACE_MISMATCH = 0x0075
DATACALLFAILCAUSE_COMPANION_IFACE_IN_USE = 0x0076
DATACALLFAILCAUSE_IP_ADDRESS_MISMATCH = 0x0077
DATACALLFAILCAUSE_IFACE_AND_POL_FAMILY_MISMATCH = 0x0078
DATACALLFAILCAUSE_EMM_ACCESS_BARRED_INFINITE_RETRY = 0x0079
DATACALLFAILCAUSE_AUTH_FAILURE_ON_EMERGENCY_CALL = 0x007a
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_1 = 0x1001
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_2 = 0x1002
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_3 = 0x1003
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_4 = 0x1004
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_5 = 0x1005
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_6 = 0x1006
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_7 = 0x1007
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_8 = 0x1008
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_9 = 0x1009
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_10 = 0x100a
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_11 = 0x100b
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_12 = 0x100c
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_13 = 0x100d
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_14 = 0x100e
DATACALLFAILCAUSE_OEM_DCFAILCAUSE_15 = 0x100f
DATACALLFAILCAUSE_ERROR_UNSPECIFIED = 0xffff
DATACALLFAILCAUSE = {
    DATACALLFAILCAUSE_TETHERED_CALL_ACTIVE: 'TETHERED_CALL_ACTIVE',
    DATACALLFAILCAUSE_RADIO_POWER_OFF: 'RADIO_POWER_OFF',
    DATACALLFAILCAUSE_PREF_RADIO_TECH_CHANGED: 'PREF_RADIO_TECH_CHANGED',
    DATACALLFAILCAUSE_SIGNAL_LOST: 'SIGNAL_LOST',
    DATACALLFAILCAUSE_DATA_REGISTRATION_FAIL: 'DATA_REGISTRATION_FAIL',
    DATACALLFAILCAUSE_VOICE_REGISTRATION_FAIL: 'VOICE_REGISTRATION_FAIL',
    DATACALLFAILCAUSE_NONE: 'NONE',
    DATACALLFAILCAUSE_OPERATOR_BARRED: 'OPERATOR_BARRED',
    DATACALLFAILCAUSE_NAS_SIGNALLING: 'NAS_SIGNALLING',
    DATACALLFAILCAUSE_LLC_SNDCP: 'LLC_SNDCP',
    DATACALLFAILCAUSE_INSUFFICIENT_RESOURCES: 'INSUFFICIENT_RESOURCES',
    DATACALLFAILCAUSE_MISSING_UKNOWN_APN: 'MISSING_UKNOWN_APN',
    DATACALLFAILCAUSE_UNKNOWN_PDP_ADDRESS_TYPE: 'UNKNOWN_PDP_ADDRESS_TYPE',
    DATACALLFAILCAUSE_USER_AUTHENTICATION: 'USER_AUTHENTICATION',
    DATACALLFAILCAUSE_ACTIVATION_REJECT_GGSN: 'ACTIVATION_REJECT_GGSN',
    DATACALLFAILCAUSE_ACTIVATION_REJECT_UNSPECIFIED: 'ACTIVATION_REJECT_UNSPECIFIED',
    DATACALLFAILCAUSE_SERVICE_OPTION_NOT_SUPPORTED: 'SERVICE_OPTION_NOT_SUPPORTED',
    DATACALLFAILCAUSE_SERVICE_OPTION_NOT_SUBSCRIBED: 'SERVICE_OPTION_NOT_SUBSCRIBED',
    DATACALLFAILCAUSE_SERVICE_OPTION_OUT_OF_ORDER: 'SERVICE_OPTION_OUT_OF_ORDER',
    DATACALLFAILCAUSE_NSAPI_IN_USE: 'NSAPI_IN_USE',
    DATACALLFAILCAUSE_REGULAR_DEACTIVATION: 'REGULAR_DEACTIVATION',
    DATACALLFAILCAUSE_QOS_NOT_ACCEPTED: 'QOS_NOT_ACCEPTED',
    DATACALLFAILCAUSE_NETWORK_FAILURE: 'NETWORK_FAILURE',
    DATACALLFAILCAUSE_UMTS_REACTIVATION_REQ: 'UMTS_REACTIVATION_REQ',
    DATACALLFAILCAUSE_FEATURE_NOT_SUPP: 'FEATURE_NOT_SUPP',
    DATACALLFAILCAUSE_TFT_SEMANTIC_ERROR: 'TFT_SEMANTIC_ERROR',
    DATACALLFAILCAUSE_TFT_SYTAX_ERROR: 'TFT_SYTAX_ERROR',
    DATACALLFAILCAUSE_UNKNOWN_PDP_CONTEXT: 'UNKNOWN_PDP_CONTEXT',
    DATACALLFAILCAUSE_FILTER_SEMANTIC_ERROR: 'FILTER_SEMANTIC_ERROR',
    DATACALLFAILCAUSE_FILTER_SYTAX_ERROR: 'FILTER_SYTAX_ERROR',
    DATACALLFAILCAUSE_PDP_WITHOUT_ACTIVE_TFT: 'PDP_WITHOUT_ACTIVE_TFT',
    DATACALLFAILCAUSE_ONLY_IPV4_ALLOWED: 'ONLY_IPV4_ALLOWED',
    DATACALLFAILCAUSE_ONLY_IPV6_ALLOWED: 'ONLY_IPV6_ALLOWED',
    DATACALLFAILCAUSE_ONLY_SINGLE_BEARER_ALLOWED: 'ONLY_SINGLE_BEARER_ALLOWED',
    DATACALLFAILCAUSE_ESM_INFO_NOT_RECEIVED: 'ESM_INFO_NOT_RECEIVED',
    DATACALLFAILCAUSE_PDN_CONN_DOES_NOT_EXIST: 'PDN_CONN_DOES_NOT_EXIST',
    DATACALLFAILCAUSE_MULTI_CONN_TO_SAME_PDN_NOT_ALLOWED: 'MULTI_CONN_TO_SAME_PDN_NOT_ALLOWED',
    DATACALLFAILCAUSE_MAX_ACTIVE_PDP_CONTEXT_REACHED: 'MAX_ACTIVE_PDP_CONTEXT_REACHED',
    DATACALLFAILCAUSE_UNSUPPORTED_APN_IN_CURRENT_PLMN: 'UNSUPPORTED_APN_IN_CURRENT_PLMN',
    DATACALLFAILCAUSE_INVALID_TRANSACTION_ID: 'INVALID_TRANSACTION_ID',
    DATACALLFAILCAUSE_MESSAGE_INCORRECT_SEMANTIC: 'MESSAGE_INCORRECT_SEMANTIC',
    DATACALLFAILCAUSE_INVALID_MANDATORY_INFO: 'INVALID_MANDATORY_INFO',
    DATACALLFAILCAUSE_MESSAGE_TYPE_UNSUPPORTED: 'MESSAGE_TYPE_UNSUPPORTED',
    DATACALLFAILCAUSE_MSG_TYPE_NONCOMPATIBLE_STATE: 'MSG_TYPE_NONCOMPATIBLE_STATE',
    DATACALLFAILCAUSE_UNKNOWN_INFO_ELEMENT: 'UNKNOWN_INFO_ELEMENT',
    DATACALLFAILCAUSE_CONDITIONAL_IE_ERROR: 'CONDITIONAL_IE_ERROR',
    DATACALLFAILCAUSE_MSG_AND_PROTOCOL_STATE_UNCOMPATIBLE: 'MSG_AND_PROTOCOL_STATE_UNCOMPATIBLE',
    DATACALLFAILCAUSE_PROTOCOL_ERRORS: 'PROTOCOL_ERRORS',
    DATACALLFAILCAUSE_APN_TYPE_CONFLICT: 'APN_TYPE_CONFLICT',
    DATACALLFAILCAUSE_INVALID_PCSCF_ADDR: 'INVALID_PCSCF_ADDR',
    DATACALLFAILCAUSE_INTERNAL_CALL_PREEMPT_BY_HIGH_PRIO_APN: 'INTERNAL_CALL_PREEMPT_BY_HIGH_PRIO_APN',
    DATACALLFAILCAUSE_EMM_ACCESS_BARRED: 'EMM_ACCESS_BARRED',
    DATACALLFAILCAUSE_EMERGENCY_IFACE_ONLY: 'EMERGENCY_IFACE_ONLY',
    DATACALLFAILCAUSE_IFACE_MISMATCH: 'IFACE_MISMATCH',
    DATACALLFAILCAUSE_COMPANION_IFACE_IN_USE: 'COMPANION_IFACE_IN_USE',
    DATACALLFAILCAUSE_IP_ADDRESS_MISMATCH: 'IP_ADDRESS_MISMATCH',
    DATACALLFAILCAUSE_IFACE_AND_POL_FAMILY_MISMATCH: 'IFACE_AND_POL_FAMILY_MISMATCH',
    DATACALLFAILCAUSE_EMM_ACCESS_BARRED_INFINITE_RETRY: 'EMM_ACCESS_BARRED_INFINITE_RETRY',
    DATACALLFAILCAUSE_AUTH_FAILURE_ON_EMERGENCY_CALL: 'AUTH_FAILURE_ON_EMERGENCY_CALL',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_1: 'OEM_DCFAILCAUSE_1',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_2: 'OEM_DCFAILCAUSE_2',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_3: 'OEM_DCFAILCAUSE_3',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_4: 'OEM_DCFAILCAUSE_4',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_5: 'OEM_DCFAILCAUSE_5',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_6: 'OEM_DCFAILCAUSE_6',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_7: 'OEM_DCFAILCAUSE_7',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_8: 'OEM_DCFAILCAUSE_8',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_9: 'OEM_DCFAILCAUSE_9',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_10: 'OEM_DCFAILCAUSE_10',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_11: 'OEM_DCFAILCAUSE_11',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_12: 'OEM_DCFAILCAUSE_12',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_13: 'OEM_DCFAILCAUSE_13',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_14: 'OEM_DCFAILCAUSE_14',
    DATACALLFAILCAUSE_OEM_DCFAILCAUSE_15: 'OEM_DCFAILCAUSE_15',
    DATACALLFAILCAUSE_ERROR_UNSPECIFIED: 'ERROR_UNSPECIFIED'
}
# DATAPROFILE
DATAPROFILE_DEFAULT = 0x0000
DATAPROFILE_TETHERED = 0x0001
DATAPROFILE_IMS = 0x0002
DATAPROFILE_FOTA = 0x0003
DATAPROFILE_CBS = 0x0004
DATAPROFILE_OEM_BASE = 0x03e8
DATAPROFILE_INVALID = 0xffffffff
DATAPROFILE = {
    DATAPROFILE_DEFAULT: 'DEFAULT',
    DATAPROFILE_TETHERED: 'TETHERED',
    DATAPROFILE_IMS: 'IMS',
    DATAPROFILE_FOTA: 'FOTA',
    DATAPROFILE_CBS: 'CBS',
    DATAPROFILE_OEM_BASE: 'OEM_BASE',
    DATAPROFILE_INVALID: 'INVALID'
}
# CARDSTATE
CARDSTATE_ABSENT = 0x0000
CARDSTATE_PRESENT = 0x0001
CARDSTATE_ERROR = 0x0002
CARDSTATE_RESTRICTED = 0x0003
CARDSTATE = {
    CARDSTATE_ABSENT: 'ABSENT',
    CARDSTATE_PRESENT: 'PRESENT',
    CARDSTATE_ERROR: 'ERROR',
    CARDSTATE_RESTRICTED: 'RESTRICTED'
}
# PERSOSUBSTATE
PERSOSUBSTATE_UNKNOWN = 0x0000
PERSOSUBSTATE_IN_PROGRESS = 0x0001
PERSOSUBSTATE_READY = 0x0002
PERSOSUBSTATE_SIM_NETWORK = 0x0003
PERSOSUBSTATE_SIM_NETWORK_SUBSET = 0x0004
PERSOSUBSTATE_SIM_CORPORATE = 0x0005
PERSOSUBSTATE_SIM_SERVICE_PROVIDER = 0x0006
PERSOSUBSTATE_SIM_SIM = 0x0007
PERSOSUBSTATE_SIM_NETWORK_PUK = 0x0008
PERSOSUBSTATE_SIM_NETWORK_SUBSET_PUK = 0x0009
PERSOSUBSTATE_SIM_CORPORATE_PUK = 0x000a
PERSOSUBSTATE_SIM_SERVICE_PROVIDER_PUK = 0x000b
PERSOSUBSTATE_SIM_SIM_PUK = 0x000c
PERSOSUBSTATE_RUIM_NETWORK1 = 0x000d
PERSOSUBSTATE_RUIM_NETWORK2 = 0x000e
PERSOSUBSTATE_RUIM_HRPD = 0x000f
PERSOSUBSTATE_RUIM_CORPORATE = 0x0010
PERSOSUBSTATE_RUIM_SERVICE_PROVIDER = 0x0011
PERSOSUBSTATE_RUIM_RUIM = 0x0012
PERSOSUBSTATE_RUIM_NETWORK1_PUK = 0x0013
PERSOSUBSTATE_RUIM_NETWORK2_PUK = 0x0014
PERSOSUBSTATE_RUIM_HRPD_PUK = 0x0015
PERSOSUBSTATE_RUIM_CORPORATE_PUK = 0x0016
PERSOSUBSTATE_RUIM_SERVICE_PROVIDER_PUK = 0x0017
PERSOSUBSTATE_RUIM_RUIM_PUK = 0x0018
PERSOSUBSTATE = {
    PERSOSUBSTATE_UNKNOWN: 'UNKNOWN',
    PERSOSUBSTATE_IN_PROGRESS: 'IN_PROGRESS',
    PERSOSUBSTATE_READY: 'READY',
    PERSOSUBSTATE_SIM_NETWORK: 'SIM_NETWORK',
    PERSOSUBSTATE_SIM_NETWORK_SUBSET: 'SIM_NETWORK_SUBSET',
    PERSOSUBSTATE_SIM_CORPORATE: 'SIM_CORPORATE',
    PERSOSUBSTATE_SIM_SERVICE_PROVIDER: 'SIM_SERVICE_PROVIDER',
    PERSOSUBSTATE_SIM_SIM: 'SIM_SIM',
    PERSOSUBSTATE_SIM_NETWORK_PUK: 'SIM_NETWORK_PUK',
    PERSOSUBSTATE_SIM_NETWORK_SUBSET_PUK: 'SIM_NETWORK_SUBSET_PUK',
    PERSOSUBSTATE_SIM_CORPORATE_PUK: 'SIM_CORPORATE_PUK',
    PERSOSUBSTATE_SIM_SERVICE_PROVIDER_PUK: 'SIM_SERVICE_PROVIDER_PUK',
    PERSOSUBSTATE_SIM_SIM_PUK: 'SIM_SIM_PUK',
    PERSOSUBSTATE_RUIM_NETWORK1: 'RUIM_NETWORK1',
    PERSOSUBSTATE_RUIM_NETWORK2: 'RUIM_NETWORK2',
    PERSOSUBSTATE_RUIM_HRPD: 'RUIM_HRPD',
    PERSOSUBSTATE_RUIM_CORPORATE: 'RUIM_CORPORATE',
    PERSOSUBSTATE_RUIM_SERVICE_PROVIDER: 'RUIM_SERVICE_PROVIDER',
    PERSOSUBSTATE_RUIM_RUIM: 'RUIM_RUIM',
    PERSOSUBSTATE_RUIM_NETWORK1_PUK: 'RUIM_NETWORK1_PUK',
    PERSOSUBSTATE_RUIM_NETWORK2_PUK: 'RUIM_NETWORK2_PUK',
    PERSOSUBSTATE_RUIM_HRPD_PUK: 'RUIM_HRPD_PUK',
    PERSOSUBSTATE_RUIM_CORPORATE_PUK: 'RUIM_CORPORATE_PUK',
    PERSOSUBSTATE_RUIM_SERVICE_PROVIDER_PUK: 'RUIM_SERVICE_PROVIDER_PUK',
    PERSOSUBSTATE_RUIM_RUIM_PUK: 'RUIM_RUIM_PUK'
}
# APPSTATE
APPSTATE_UNKNOWN = 0x0000
APPSTATE_DETECTED = 0x0001
APPSTATE_PIN = 0x0002
APPSTATE_PUK = 0x0003
APPSTATE_SUBSCRIPTION_PERSO = 0x0004
APPSTATE_READY = 0x0005
APPSTATE = {
    APPSTATE_UNKNOWN: 'UNKNOWN',
    APPSTATE_DETECTED: 'DETECTED',
    APPSTATE_PIN: 'PIN',
    APPSTATE_PUK: 'PUK',
    APPSTATE_SUBSCRIPTION_PERSO: 'SUBSCRIPTION_PERSO',
    APPSTATE_READY: 'READY'
}
# PINSTATE
PINSTATE_UNKNOWN = 0x0000
PINSTATE_ENABLED_NOT_VERIFIED = 0x0001
PINSTATE_ENABLED_VERIFIED = 0x0002
PINSTATE_DISABLED = 0x0003
PINSTATE_ENABLED_BLOCKED = 0x0004
PINSTATE_ENABLED_PERM_BLOCKED = 0x0005
PINSTATE = {
    PINSTATE_UNKNOWN: 'UNKNOWN',
    PINSTATE_ENABLED_NOT_VERIFIED: 'ENABLED_NOT_VERIFIED',
    PINSTATE_ENABLED_VERIFIED: 'ENABLED_VERIFIED',
    PINSTATE_DISABLED: 'DISABLED',
    PINSTATE_ENABLED_BLOCKED: 'ENABLED_BLOCKED',
    PINSTATE_ENABLED_PERM_BLOCKED: 'ENABLED_PERM_BLOCKED'
}
# APPTYPE
APPTYPE_UNKNOWN = 0x0000
APPTYPE_SIM = 0x0001
APPTYPE_USIM = 0x0002
APPTYPE_RUIM = 0x0003
APPTYPE_CSIM = 0x0004
APPTYPE_ISIM = 0x0005
APPTYPE = {
    APPTYPE_UNKNOWN: 'UNKNOWN',
    APPTYPE_SIM: 'SIM',
    APPTYPE_USIM: 'USIM',
    APPTYPE_RUIM: 'RUIM',
    APPTYPE_CSIM: 'CSIM',
    APPTYPE_ISIM: 'ISIM'
}
# SIMREFRESHRESULT
SIMREFRESHRESULT_FILE_UPDATE = 0x0000
SIMREFRESHRESULT_INIT = 0x0001
SIMREFRESHRESULT_RESET = 0x0002
SIMREFRESHRESULT = {
    SIMREFRESHRESULT_FILE_UPDATE: 'FILE_UPDATE',
    SIMREFRESHRESULT_INIT: 'INIT',
    SIMREFRESHRESULT_RESET: 'RESET'
}
# CDMA_OTA_PROVISIONSTATUS
CDMA_OTA_PROVISIONSTATUS_OTAPA_ABORTED = 0x0000
CDMA_OTA_PROVISIONSTATUS = {
    CDMA_OTA_PROVISIONSTATUS_OTAPA_ABORTED: 'OTAPA_ABORTED'
}
# CELLINFOTYPE
CELLINFOTYPE_GSM = 0x0001
CELLINFOTYPE_CDMA = 0x0002
CELLINFOTYPE_LTE = 0x0003
CELLINFOTYPE_WCDMA = 0x0004
CELLINFOTYPE_TD_SCDMA = 0x0005
CELLINFOTYPE = {
    CELLINFOTYPE_GSM: 'GSM',
    CELLINFOTYPE_CDMA: 'CDMA',
    CELLINFOTYPE_LTE: 'LTE',
    CELLINFOTYPE_WCDMA: 'WCDMA',
    CELLINFOTYPE_TD_SCDMA: 'TD_SCDMA'
}
# TIMESTAMPTYPE
TIMESTAMPTYPE_UNKNOWN = 0x0000
TIMESTAMPTYPE_ANTENNA = 0x0001
TIMESTAMPTYPE_MODEM = 0x0002
TIMESTAMPTYPE_OEM_RIL = 0x0003
TIMESTAMPTYPE_JAVA_RIL = 0x0004
TIMESTAMPTYPE = {
    TIMESTAMPTYPE_UNKNOWN: 'UNKNOWN',
    TIMESTAMPTYPE_ANTENNA: 'ANTENNA',
    TIMESTAMPTYPE_MODEM: 'MODEM',
    TIMESTAMPTYPE_OEM_RIL: 'OEM_RIL',
    TIMESTAMPTYPE_JAVA_RIL: 'JAVA_RIL'
}
# CDMA_INFORECNAME
CDMA_INFORECNAME_T53_AUDIO_CONTROL_INFO_REC = 0x0000
CDMA_INFORECNAME = {
    CDMA_INFORECNAME_T53_AUDIO_CONTROL_INFO_REC: 'T53_AUDIO_CONTROL_INFO_REC'
}
# CDMA_REDIRECTINGREASON
CDMA_REDIRECTINGREASON_UNKNOWN = 0x0000
CDMA_REDIRECTINGREASON_CALL_FORWARDING_BUSY = 0x0001
CDMA_REDIRECTINGREASON_CALL_FORWARDING_NO_REPLY = 0x0002
CDMA_REDIRECTINGREASON_CALLED_DTE_OUT_OF_ORDER = 0x0009
CDMA_REDIRECTINGREASON_CALL_FORWARDING_BY_THE_CALLED_DTE = 0x000a
CDMA_REDIRECTINGREASON_CALL_FORWARDING_UNCONDITIONAL = 0x000f
CDMA_REDIRECTINGREASON_RESERVED = 0x0010
CDMA_REDIRECTINGREASON = {
    CDMA_REDIRECTINGREASON_UNKNOWN: 'UNKNOWN',
    CDMA_REDIRECTINGREASON_CALL_FORWARDING_BUSY: 'CALL_FORWARDING_BUSY',
    CDMA_REDIRECTINGREASON_CALL_FORWARDING_NO_REPLY: 'CALL_FORWARDING_NO_REPLY',
    CDMA_REDIRECTINGREASON_CALLED_DTE_OUT_OF_ORDER: 'CALLED_DTE_OUT_OF_ORDER',
    CDMA_REDIRECTINGREASON_CALL_FORWARDING_BY_THE_CALLED_DTE: 'CALL_FORWARDING_BY_THE_CALLED_DTE',
    CDMA_REDIRECTINGREASON_CALL_FORWARDING_UNCONDITIONAL: 'CALL_FORWARDING_UNCONDITIONAL',
    CDMA_REDIRECTINGREASON_RESERVED: 'RESERVED'
}
# SRVCCSTATE
SRVCCSTATE_HANDOVER_STARTED = 0x0000
SRVCCSTATE_HANDOVER_COMPLETED = 0x0001
SRVCCSTATE_HANDOVER_FAILED = 0x0002
SRVCCSTATE_HANDOVER_CANCELED = 0x0003
SRVCCSTATE = {
    SRVCCSTATE_HANDOVER_STARTED: 'HANDOVER_STARTED',
    SRVCCSTATE_HANDOVER_COMPLETED: 'HANDOVER_COMPLETED',
    SRVCCSTATE_HANDOVER_FAILED: 'HANDOVER_FAILED',
    SRVCCSTATE_HANDOVER_CANCELED: 'HANDOVER_CANCELED'
}
# HARDWARECONFIG_TYPE
HARDWARECONFIG_TYPE_MODEM = 0x0000
HARDWARECONFIG_TYPE_SIM = 0x0001
HARDWARECONFIG_TYPE = {
    HARDWARECONFIG_TYPE_MODEM: 'MODEM',
    HARDWARECONFIG_TYPE_SIM: 'SIM'
}
# HARDWARECONFIG_STATE
HARDWARECONFIG_STATE_STATE_ENABLED = 0x0000
HARDWARECONFIG_STATE_STATE_STANDBY = 0x0001
HARDWARECONFIG_STATE_STATE_DISABLED = 0x0002
HARDWARECONFIG_STATE = {
    HARDWARECONFIG_STATE_STATE_ENABLED: 'STATE_ENABLED',
    HARDWARECONFIG_STATE_STATE_STANDBY: 'STATE_STANDBY',
    HARDWARECONFIG_STATE_STATE_DISABLED: 'STATE_DISABLED'
}
# SSSERVICETYPE
SSSERVICETYPE_INCOMING_BARRING = 0x0000
SSSERVICETYPE = {
    SSSERVICETYPE_INCOMING_BARRING: 'INCOMING_BARRING'
}
# SSREQUESTTYPE
SSREQUESTTYPE_ERASURE = 0x0000
SSREQUESTTYPE = {
    SSREQUESTTYPE_ERASURE: 'ERASURE'
}
# SSTELESERVICETYPE
SSTELESERVICETYPE_ALL_TELESERVICES_EXCEPT_SMS = 0x0000
SSTELESERVICETYPE = {
    SSTELESERVICETYPE_ALL_TELESERVICES_EXCEPT_SMS: 'ALL_TELESERVICES_EXCEPT_SMS'
}
# DCPOWERSTATES
DCPOWERSTATES_LOW = 0x0001
DCPOWERSTATES_MEDIUM = 0x0002
DCPOWERSTATES_HIGH = 0x0003
DCPOWERSTATES_UNKNOWN = 0xffffffff
DCPOWERSTATES = {
    DCPOWERSTATES_LOW: 'LOW',
    DCPOWERSTATES_MEDIUM: 'MEDIUM',
    DCPOWERSTATES_HIGH: 'HIGH',
    DCPOWERSTATES_UNKNOWN: 'UNKNOWN'
}
# REQUEST
REQUEST_GET_SIM_STATUS = 0x0001
REQUEST_ENTER_SIM_PIN = 0x0002
REQUEST_ENTER_SIM_PUK = 0x0003
REQUEST_ENTER_SIM_PIN2 = 0x0004
REQUEST_ENTER_SIM_PUK2 = 0x0005
REQUEST_CHANGE_SIM_PIN = 0x0006
REQUEST_CHANGE_SIM_PIN2 = 0x0007
REQUEST_ENTER_NETWORK_DEPERSONALIZATION = 0x0008
REQUEST_GET_CURRENT_CALLS = 0x0009
REQUEST_DIAL = 0x000a
REQUEST_GET_IMSI = 0x000b
REQUEST_HANGUP = 0x000c
REQUEST_HANGUP_WAITING_OR_BACKGROUND = 0x000d
REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND = 0x000e
REQUEST_SWITCH_HOLDING_AND_ACTIVE = 0x000f
REQUEST_CONFERENCE = 0x0010
REQUEST_UDUB = 0x0011
REQUEST_LAST_CALL_FAIL_CAUSE = 0x0012
REQUEST_SIGNAL_STRENGTH = 0x0013
REQUEST_VOICE_REGISTRATION_STATE = 0x0014
REQUEST_DATA_REGISTRATION_STATE = 0x0015
REQUEST_OPERATOR = 0x0016
REQUEST_RADIO_POWER = 0x0017
REQUEST_DTMF = 0x0018
REQUEST_SEND_SMS = 0x0019
REQUEST_SEND_SMS_EXPECT_MORE = 0x001a
REQUEST_SETUP_DATA_CALL = 0x001b
REQUEST_SIM_IO = 0x001c
REQUEST_SEND_USSD = 0x001d
REQUEST_CANCEL_USSD = 0x001e
REQUEST_GET_CLIR = 0x001f
REQUEST_SET_CLIR = 0x0020
REQUEST_QUERY_CALL_FORWARD_STATUS = 0x0021
REQUEST_SET_CALL_FORWARD = 0x0022
REQUEST_QUERY_CALL_WAITING = 0x0023
REQUEST_SET_CALL_WAITING = 0x0024
REQUEST_SMS_ACKNOWLEDGE = 0x0025
REQUEST_GET_IMEI = 0x0026
REQUEST_GET_IMEISV = 0x0027
REQUEST_ANSWER = 0x0028
REQUEST_DEACTIVATE_DATA_CALL = 0x0029
REQUEST_QUERY_FACILITY_LOCK = 0x002a
REQUEST_SET_FACILITY_LOCK = 0x002b
REQUEST_CHANGE_BARRING_PASSWORD = 0x002c
REQUEST_QUERY_NETWORK_SELECTION_MODE = 0x002d
REQUEST_SET_NETWORK_SELECTION_AUTOMATIC = 0x002e
REQUEST_SET_NETWORK_SELECTION_MANUAL = 0x002f
REQUEST_QUERY_AVAILABLE_NETWORKS = 0x0030
REQUEST_DTMF_START = 0x0031
REQUEST_DTMF_STOP = 0x0032
REQUEST_BASEBAND_VERSION = 0x0033
REQUEST_SEPARATE_CONNECTION = 0x0034
REQUEST_SET_MUTE = 0x0035
REQUEST_GET_MUTE = 0x0036
REQUEST_QUERY_CLIP = 0x0037
REQUEST_LAST_DATA_CALL_FAIL_CAUSE = 0x0038
REQUEST_DATA_CALL_LIST = 0x0039
REQUEST_RESET_RADIO = 0x003a
REQUEST_OEM_HOOK_RAW = 0x003b
REQUEST_OEM_HOOK_STRINGS = 0x003c
REQUEST_SCREEN_STATE = 0x003d
REQUEST_SET_SUPP_SVC_NOTIFICATION = 0x003e
REQUEST_WRITE_SMS_TO_SIM = 0x003f
REQUEST_DELETE_SMS_ON_SIM = 0x0040
REQUEST_SET_BAND_MODE = 0x0041
REQUEST_QUERY_AVAILABLE_BAND_MODE = 0x0042
REQUEST_STK_GET_PROFILE = 0x0043
REQUEST_STK_SET_PROFILE = 0x0044
REQUEST_STK_SEND_ENVELOPE_COMMAND = 0x0045
REQUEST_STK_SEND_TERMINAL_RESPONSE = 0x0046
REQUEST_STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM = 0x0047
REQUEST_EXPLICIT_CALL_TRANSFER = 0x0048
REQUEST_SET_PREFERRED_NETWORK_TYPE = 0x0049
REQUEST_GET_PREFERRED_NETWORK_TYPE = 0x004a
REQUEST_GET_NEIGHBORING_CELL_IDS = 0x004b
REQUEST_SET_LOCATION_UPDATES = 0x004c
REQUEST_CDMA_SET_SUBSCRIPTION_SOURCE = 0x004d
REQUEST_CDMA_SET_ROAMING_PREFERENCE = 0x004e
REQUEST_CDMA_QUERY_ROAMING_PREFERENCE = 0x004f
REQUEST_SET_TTY_MODE = 0x0050
REQUEST_QUERY_TTY_MODE = 0x0051
REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE = 0x0052
REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE = 0x0053
REQUEST_CDMA_FLASH = 0x0054
REQUEST_CDMA_BURST_DTMF = 0x0055
REQUEST_CDMA_VALIDATE_AND_WRITE_AKEY = 0x0056
REQUEST_CDMA_SEND_SMS = 0x0057
REQUEST_CDMA_SMS_ACKNOWLEDGE = 0x0058
REQUEST_GSM_GET_BROADCAST_SMS_CONFIG = 0x0059
REQUEST_GSM_SET_BROADCAST_SMS_CONFIG = 0x005a
REQUEST_GSM_SMS_BROADCAST_ACTIVATION = 0x005b
REQUEST_CDMA_GET_BROADCAST_SMS_CONFIG = 0x005c
REQUEST_CDMA_SET_BROADCAST_SMS_CONFIG = 0x005d
REQUEST_CDMA_SMS_BROADCAST_ACTIVATION = 0x005e
REQUEST_CDMA_SUBSCRIPTION = 0x005f
REQUEST_CDMA_WRITE_SMS_TO_RUIM = 0x0060
REQUEST_CDMA_DELETE_SMS_ON_RUIM = 0x0061
REQUEST_DEVICE_IDENTITY = 0x0062
REQUEST_EXIT_EMERGENCY_CALLBACK_MODE = 0x0063
REQUEST_GET_SMSC_ADDRESS = 0x0064
REQUEST_SET_SMSC_ADDRESS = 0x0065
REQUEST_REPORT_SMS_MEMORY_STATUS = 0x0066
REQUEST_REPORT_STK_SERVICE_IS_RUNNING = 0x0067
REQUEST_CDMA_GET_SUBSCRIPTION_SOURCE = 0x0068
REQUEST_ISIM_AUTHENTICATION = 0x0069
REQUEST_ACKNOWLEDGE_INCOMING_GSM_SMS_WITH_PDU = 0x006a
REQUEST_STK_SEND_ENVELOPE_WITH_STATUS = 0x006b
REQUEST_VOICE_RADIO_TECH = 0x006c
REQUEST_GET_CELL_INFO_LIST = 0x006d
REQUEST_SET_UNSOL_CELL_INFO_LIST_RATE = 0x006e
REQUEST_SET_INITIAL_ATTACH_APN = 0x006f
REQUEST_IMS_REGISTRATION_STATE = 0x0070
REQUEST_IMS_SEND_SMS = 0x0071
REQUEST_SIM_TRANSMIT_APDU_BASIC = 0x0072
REQUEST_SIM_OPEN_CHANNEL = 0x0073
REQUEST_SIM_CLOSE_CHANNEL = 0x0074
REQUEST_SIM_TRANSMIT_APDU_CHANNEL = 0x0075
REQUEST_NV_READ_ITEM = 0x0076
REQUEST_NV_WRITE_ITEM = 0x0077
REQUEST_NV_WRITE_CDMA_PRL = 0x0078
REQUEST_NV_RESET_CONFIG = 0x0079
REQUEST_SET_UICC_SUBSCRIPTION = 0x007a
REQUEST_ALLOW_DATA = 0x007b
REQUEST_GET_HARDWARE_CONFIG = 0x007c
REQUEST_SIM_AUTHENTICATION = 0x007d
REQUEST_GET_DC_RT_INFO = 0x007e
REQUEST_SET_DC_RT_INFO_RATE = 0x007f
REQUEST_SET_DATA_PROFILE = 0x0080
REQUEST_SHUTDOWN = 0x0081
REQUEST_GET_RADIO_CAPABILITY = 0x0082
REQUEST_SET_RADIO_CAPABILITY = 0x0083
REQUEST_START_LCE = 0x0084
REQUEST_STOP_LCE = 0x0085
REQUEST_PULL_LCEDATA = 0x0086
REQUEST_GET_ACTIVITY_INFO = 0x0087
REQUEST_SET_CARRIER_RESTRICTIONS = 0x0088
REQUEST_GET_CARRIER_RESTRICTIONS = 0x0089
REQUEST = {
    REQUEST_GET_SIM_STATUS: 'GET_SIM_STATUS',
    REQUEST_ENTER_SIM_PIN: 'ENTER_SIM_PIN',
    REQUEST_ENTER_SIM_PUK: 'ENTER_SIM_PUK',
    REQUEST_ENTER_SIM_PIN2: 'ENTER_SIM_PIN2',
    REQUEST_ENTER_SIM_PUK2: 'ENTER_SIM_PUK2',
    REQUEST_CHANGE_SIM_PIN: 'CHANGE_SIM_PIN',
    REQUEST_CHANGE_SIM_PIN2: 'CHANGE_SIM_PIN2',
    REQUEST_ENTER_NETWORK_DEPERSONALIZATION: 'ENTER_NETWORK_DEPERSONALIZATION',
    REQUEST_GET_CURRENT_CALLS: 'GET_CURRENT_CALLS',
    REQUEST_DIAL: 'DIAL',
    REQUEST_GET_IMSI: 'GET_IMSI',
    REQUEST_HANGUP: 'HANGUP',
    REQUEST_HANGUP_WAITING_OR_BACKGROUND: 'HANGUP_WAITING_OR_BACKGROUND',
    REQUEST_HANGUP_FOREGROUND_RESUME_BACKGROUND: 'HANGUP_FOREGROUND_RESUME_BACKGROUND',
    REQUEST_SWITCH_HOLDING_AND_ACTIVE: 'SWITCH_HOLDING_AND_ACTIVE',
    REQUEST_CONFERENCE: 'CONFERENCE',
    REQUEST_UDUB: 'UDUB',
    REQUEST_LAST_CALL_FAIL_CAUSE: 'LAST_CALL_FAIL_CAUSE',
    REQUEST_SIGNAL_STRENGTH: 'SIGNAL_STRENGTH',
    REQUEST_VOICE_REGISTRATION_STATE: 'VOICE_REGISTRATION_STATE',
    REQUEST_DATA_REGISTRATION_STATE: 'DATA_REGISTRATION_STATE',
    REQUEST_OPERATOR: 'OPERATOR',
    REQUEST_RADIO_POWER: 'RADIO_POWER',
    REQUEST_DTMF: 'DTMF',
    REQUEST_SEND_SMS: 'SEND_SMS',
    REQUEST_SEND_SMS_EXPECT_MORE: 'SEND_SMS_EXPECT_MORE',
    REQUEST_SETUP_DATA_CALL: 'SETUP_DATA_CALL',
    REQUEST_SIM_IO: 'SIM_IO',
    REQUEST_SEND_USSD: 'SEND_USSD',
    REQUEST_CANCEL_USSD: 'CANCEL_USSD',
    REQUEST_GET_CLIR: 'GET_CLIR',
    REQUEST_SET_CLIR: 'SET_CLIR',
    REQUEST_QUERY_CALL_FORWARD_STATUS: 'QUERY_CALL_FORWARD_STATUS',
    REQUEST_SET_CALL_FORWARD: 'SET_CALL_FORWARD',
    REQUEST_QUERY_CALL_WAITING: 'QUERY_CALL_WAITING',
    REQUEST_SET_CALL_WAITING: 'SET_CALL_WAITING',
    REQUEST_SMS_ACKNOWLEDGE: 'SMS_ACKNOWLEDGE',
    REQUEST_GET_IMEI: 'GET_IMEI',
    REQUEST_GET_IMEISV: 'GET_IMEISV',
    REQUEST_ANSWER: 'ANSWER',
    REQUEST_DEACTIVATE_DATA_CALL: 'DEACTIVATE_DATA_CALL',
    REQUEST_QUERY_FACILITY_LOCK: 'QUERY_FACILITY_LOCK',
    REQUEST_SET_FACILITY_LOCK: 'SET_FACILITY_LOCK',
    REQUEST_CHANGE_BARRING_PASSWORD: 'CHANGE_BARRING_PASSWORD',
    REQUEST_QUERY_NETWORK_SELECTION_MODE: 'QUERY_NETWORK_SELECTION_MODE',
    REQUEST_SET_NETWORK_SELECTION_AUTOMATIC: 'SET_NETWORK_SELECTION_AUTOMATIC',
    REQUEST_SET_NETWORK_SELECTION_MANUAL: 'SET_NETWORK_SELECTION_MANUAL',
    REQUEST_QUERY_AVAILABLE_NETWORKS: 'QUERY_AVAILABLE_NETWORKS',
    REQUEST_DTMF_START: 'DTMF_START',
    REQUEST_DTMF_STOP: 'DTMF_STOP',
    REQUEST_BASEBAND_VERSION: 'BASEBAND_VERSION',
    REQUEST_SEPARATE_CONNECTION: 'SEPARATE_CONNECTION',
    REQUEST_SET_MUTE: 'SET_MUTE',
    REQUEST_GET_MUTE: 'GET_MUTE',
    REQUEST_QUERY_CLIP: 'QUERY_CLIP',
    REQUEST_LAST_DATA_CALL_FAIL_CAUSE: 'LAST_DATA_CALL_FAIL_CAUSE',
    REQUEST_DATA_CALL_LIST: 'DATA_CALL_LIST',
    REQUEST_RESET_RADIO: 'RESET_RADIO',
    REQUEST_OEM_HOOK_RAW: 'OEM_HOOK_RAW',
    REQUEST_OEM_HOOK_STRINGS: 'OEM_HOOK_STRINGS',
    REQUEST_SCREEN_STATE: 'SCREEN_STATE',
    REQUEST_SET_SUPP_SVC_NOTIFICATION: 'SET_SUPP_SVC_NOTIFICATION',
    REQUEST_WRITE_SMS_TO_SIM: 'WRITE_SMS_TO_SIM',
    REQUEST_DELETE_SMS_ON_SIM: 'DELETE_SMS_ON_SIM',
    REQUEST_SET_BAND_MODE: 'SET_BAND_MODE',
    REQUEST_QUERY_AVAILABLE_BAND_MODE: 'QUERY_AVAILABLE_BAND_MODE',
    REQUEST_STK_GET_PROFILE: 'STK_GET_PROFILE',
    REQUEST_STK_SET_PROFILE: 'STK_SET_PROFILE',
    REQUEST_STK_SEND_ENVELOPE_COMMAND: 'STK_SEND_ENVELOPE_COMMAND',
    REQUEST_STK_SEND_TERMINAL_RESPONSE: 'STK_SEND_TERMINAL_RESPONSE',
    REQUEST_STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM: 'STK_HANDLE_CALL_SETUP_REQUESTED_FROM_SIM',
    REQUEST_EXPLICIT_CALL_TRANSFER: 'EXPLICIT_CALL_TRANSFER',
    REQUEST_SET_PREFERRED_NETWORK_TYPE: 'SET_PREFERRED_NETWORK_TYPE',
    REQUEST_GET_PREFERRED_NETWORK_TYPE: 'GET_PREFERRED_NETWORK_TYPE',
    REQUEST_GET_NEIGHBORING_CELL_IDS: 'GET_NEIGHBORING_CELL_IDS',
    REQUEST_SET_LOCATION_UPDATES: 'SET_LOCATION_UPDATES',
    REQUEST_CDMA_SET_SUBSCRIPTION_SOURCE: 'CDMA_SET_SUBSCRIPTION_SOURCE',
    REQUEST_CDMA_SET_ROAMING_PREFERENCE: 'CDMA_SET_ROAMING_PREFERENCE',
    REQUEST_CDMA_QUERY_ROAMING_PREFERENCE: 'CDMA_QUERY_ROAMING_PREFERENCE',
    REQUEST_SET_TTY_MODE: 'SET_TTY_MODE',
    REQUEST_QUERY_TTY_MODE: 'QUERY_TTY_MODE',
    REQUEST_CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE: 'CDMA_SET_PREFERRED_VOICE_PRIVACY_MODE',
    REQUEST_CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE: 'CDMA_QUERY_PREFERRED_VOICE_PRIVACY_MODE',
    REQUEST_CDMA_FLASH: 'CDMA_FLASH',
    REQUEST_CDMA_BURST_DTMF: 'CDMA_BURST_DTMF',
    REQUEST_CDMA_VALIDATE_AND_WRITE_AKEY: 'CDMA_VALIDATE_AND_WRITE_AKEY',
    REQUEST_CDMA_SEND_SMS: 'CDMA_SEND_SMS',
    REQUEST_CDMA_SMS_ACKNOWLEDGE: 'CDMA_SMS_ACKNOWLEDGE',
    REQUEST_GSM_GET_BROADCAST_SMS_CONFIG: 'GSM_GET_BROADCAST_SMS_CONFIG',
    REQUEST_GSM_SET_BROADCAST_SMS_CONFIG: 'GSM_SET_BROADCAST_SMS_CONFIG',
    REQUEST_GSM_SMS_BROADCAST_ACTIVATION: 'GSM_SMS_BROADCAST_ACTIVATION',
    REQUEST_CDMA_GET_BROADCAST_SMS_CONFIG: 'CDMA_GET_BROADCAST_SMS_CONFIG',
    REQUEST_CDMA_SET_BROADCAST_SMS_CONFIG: 'CDMA_SET_BROADCAST_SMS_CONFIG',
    REQUEST_CDMA_SMS_BROADCAST_ACTIVATION: 'CDMA_SMS_BROADCAST_ACTIVATION',
    REQUEST_CDMA_SUBSCRIPTION: 'CDMA_SUBSCRIPTION',
    REQUEST_CDMA_WRITE_SMS_TO_RUIM: 'CDMA_WRITE_SMS_TO_RUIM',
    REQUEST_CDMA_DELETE_SMS_ON_RUIM: 'CDMA_DELETE_SMS_ON_RUIM',
    REQUEST_DEVICE_IDENTITY: 'DEVICE_IDENTITY',
    REQUEST_EXIT_EMERGENCY_CALLBACK_MODE: 'EXIT_EMERGENCY_CALLBACK_MODE',
    REQUEST_GET_SMSC_ADDRESS: 'GET_SMSC_ADDRESS',
    REQUEST_SET_SMSC_ADDRESS: 'SET_SMSC_ADDRESS',
    REQUEST_REPORT_SMS_MEMORY_STATUS: 'REPORT_SMS_MEMORY_STATUS',
    REQUEST_REPORT_STK_SERVICE_IS_RUNNING: 'REPORT_STK_SERVICE_IS_RUNNING',
    REQUEST_CDMA_GET_SUBSCRIPTION_SOURCE: 'CDMA_GET_SUBSCRIPTION_SOURCE',
    REQUEST_ISIM_AUTHENTICATION: 'ISIM_AUTHENTICATION',
    REQUEST_ACKNOWLEDGE_INCOMING_GSM_SMS_WITH_PDU: 'ACKNOWLEDGE_INCOMING_GSM_SMS_WITH_PDU',
    REQUEST_STK_SEND_ENVELOPE_WITH_STATUS: 'STK_SEND_ENVELOPE_WITH_STATUS',
    REQUEST_VOICE_RADIO_TECH: 'VOICE_RADIO_TECH',
    REQUEST_GET_CELL_INFO_LIST: 'GET_CELL_INFO_LIST',
    REQUEST_SET_UNSOL_CELL_INFO_LIST_RATE: 'SET_UNSOL_CELL_INFO_LIST_RATE',
    REQUEST_SET_INITIAL_ATTACH_APN: 'SET_INITIAL_ATTACH_APN',
    REQUEST_IMS_REGISTRATION_STATE: 'IMS_REGISTRATION_STATE',
    REQUEST_IMS_SEND_SMS: 'IMS_SEND_SMS',
    REQUEST_SIM_TRANSMIT_APDU_BASIC: 'SIM_TRANSMIT_APDU_BASIC',
    REQUEST_SIM_OPEN_CHANNEL: 'SIM_OPEN_CHANNEL',
    REQUEST_SIM_CLOSE_CHANNEL: 'SIM_CLOSE_CHANNEL',
    REQUEST_SIM_TRANSMIT_APDU_CHANNEL: 'SIM_TRANSMIT_APDU_CHANNEL',
    REQUEST_NV_READ_ITEM: 'NV_READ_ITEM',
    REQUEST_NV_WRITE_ITEM: 'NV_WRITE_ITEM',
    REQUEST_NV_WRITE_CDMA_PRL: 'NV_WRITE_CDMA_PRL',
    REQUEST_NV_RESET_CONFIG: 'NV_RESET_CONFIG',
    REQUEST_SET_UICC_SUBSCRIPTION: 'SET_UICC_SUBSCRIPTION',
    REQUEST_ALLOW_DATA: 'ALLOW_DATA',
    REQUEST_GET_HARDWARE_CONFIG: 'GET_HARDWARE_CONFIG',
    REQUEST_SIM_AUTHENTICATION: 'SIM_AUTHENTICATION',
    REQUEST_GET_DC_RT_INFO: 'GET_DC_RT_INFO',
    REQUEST_SET_DC_RT_INFO_RATE: 'SET_DC_RT_INFO_RATE',
    REQUEST_SET_DATA_PROFILE: 'SET_DATA_PROFILE',
    REQUEST_SHUTDOWN: 'SHUTDOWN',
    REQUEST_GET_RADIO_CAPABILITY: 'GET_RADIO_CAPABILITY',
    REQUEST_SET_RADIO_CAPABILITY: 'SET_RADIO_CAPABILITY',
    REQUEST_START_LCE: 'START_LCE',
    REQUEST_STOP_LCE: 'STOP_LCE',
    REQUEST_PULL_LCEDATA: 'PULL_LCEDATA',
    REQUEST_GET_ACTIVITY_INFO: 'GET_ACTIVITY_INFO',
    REQUEST_SET_CARRIER_RESTRICTIONS: 'SET_CARRIER_RESTRICTIONS',
    REQUEST_GET_CARRIER_RESTRICTIONS: 'GET_CARRIER_RESTRICTIONS'
}
# RESPONSE
RESPONSE_ACKNOWLEDGEMENT = 0x0320
RESPONSE = {
    RESPONSE_ACKNOWLEDGEMENT: 'ACKNOWLEDGEMENT'
}
# UNSOL
UNSOL_RESPONSE_RADIO_STATE_CHANGED = 0x03e8
UNSOL_RESPONSE_CALL_STATE_CHANGED = 0x03e9
UNSOL_RESPONSE_VOICE_NETWORK_STATE_CHANGED = 0x03ea
UNSOL_RESPONSE_NEW_SMS = 0x03eb
UNSOL_RESPONSE_NEW_SMS_STATUS_REPORT = 0x03ec
UNSOL_RESPONSE_NEW_SMS_ON_SIM = 0x03ed
UNSOL_ON_USSD = 0x03ee
UNSOL_ON_USSD_REQUEST = 0x03ef
UNSOL_NITZ_TIME_RECEIVED = 0x03f0
UNSOL_SIGNAL_STRENGTH = 0x03f1
UNSOL_DATA_CALL_LIST_CHANGED = 0x03f2
UNSOL_SUPP_SVC_NOTIFICATION = 0x03f3
UNSOL_STK_SESSION_END = 0x03f4
UNSOL_STK_PROACTIVE_COMMAND = 0x03f5
UNSOL_STK_EVENT_NOTIFY = 0x03f6
UNSOL_STK_CALL_SETUP = 0x03f7
UNSOL_SIM_SMS_STORAGE_FULL = 0x03f8
UNSOL_SIM_REFRESH = 0x03f9
UNSOL_CALL_RING = 0x03fa
UNSOL_RESPONSE_SIM_STATUS_CHANGED = 0x03fb
UNSOL_RESPONSE_CDMA_NEW_SMS = 0x03fc
UNSOL_RESPONSE_NEW_BROADCAST_SMS = 0x03fd
UNSOL_CDMA_RUIM_SMS_STORAGE_FULL = 0x03fe
UNSOL_RESTRICTED_STATE_CHANGED = 0x03ff
UNSOL_ENTER_EMERGENCY_CALLBACK_MODE = 0x0400
UNSOL_CDMA_CALL_WAITING = 0x0401
UNSOL_CDMA_OTA_PROVISION_STATUS = 0x0402
UNSOL_CDMA_INFO_REC = 0x0403
UNSOL_OEM_HOOK_RAW = 0x0404
UNSOL_RINGBACK_TONE = 0x0405
UNSOL_RESEND_INCALL_MUTE = 0x0406
UNSOL_CDMA_SUBSCRIPTION_SOURCE_CHANGED = 0x0407
UNSOL_CDMA_PRL_CHANGED = 0x0408
UNSOL_EXIT_EMERGENCY_CALLBACK_MODE = 0x0409
UNSOL_RIL_CONNECTED = 0x040a
UNSOL_VOICE_RADIO_TECH_CHANGED = 0x040b
UNSOL_CELL_INFO_LIST = 0x040c
UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED = 0x040d
UNSOL_UICC_SUBSCRIPTION_STATUS_CHANGED = 0x040e
UNSOL_SRVCC_STATE_NOTIFY = 0x040f
UNSOL_HARDWARE_CONFIG_CHANGED = 0x0410
UNSOL_DC_RT_INFO_CHANGED = 0x0411
UNSOL_RADIO_CAPABILITY = 0x0412
UNSOL_ON_SS = 0x0413
UNSOL_STK_CC_ALPHA_NOTIFY = 0x0414
UNSOL_LCEDATA_RECV = 0x0415
UNSOL_PCO_DATA = 0x0416
UNSOL = {
    UNSOL_RESPONSE_RADIO_STATE_CHANGED: 'RESPONSE_RADIO_STATE_CHANGED',
    UNSOL_RESPONSE_CALL_STATE_CHANGED: 'RESPONSE_CALL_STATE_CHANGED',
    UNSOL_RESPONSE_VOICE_NETWORK_STATE_CHANGED: 'RESPONSE_VOICE_NETWORK_STATE_CHANGED',
    UNSOL_RESPONSE_NEW_SMS: 'RESPONSE_NEW_SMS',
    UNSOL_RESPONSE_NEW_SMS_STATUS_REPORT: 'RESPONSE_NEW_SMS_STATUS_REPORT',
    UNSOL_RESPONSE_NEW_SMS_ON_SIM: 'RESPONSE_NEW_SMS_ON_SIM',
    UNSOL_ON_USSD: 'ON_USSD',
    UNSOL_ON_USSD_REQUEST: 'ON_USSD_REQUEST',
    UNSOL_NITZ_TIME_RECEIVED: 'NITZ_TIME_RECEIVED',
    UNSOL_SIGNAL_STRENGTH: 'SIGNAL_STRENGTH',
    UNSOL_DATA_CALL_LIST_CHANGED: 'DATA_CALL_LIST_CHANGED',
    UNSOL_SUPP_SVC_NOTIFICATION: 'SUPP_SVC_NOTIFICATION',
    UNSOL_STK_SESSION_END: 'STK_SESSION_END',
    UNSOL_STK_PROACTIVE_COMMAND: 'STK_PROACTIVE_COMMAND',
    UNSOL_STK_EVENT_NOTIFY: 'STK_EVENT_NOTIFY',
    UNSOL_STK_CALL_SETUP: 'STK_CALL_SETUP',
    UNSOL_SIM_SMS_STORAGE_FULL: 'SIM_SMS_STORAGE_FULL',
    UNSOL_SIM_REFRESH: 'SIM_REFRESH',
    UNSOL_CALL_RING: 'CALL_RING',
    UNSOL_RESPONSE_SIM_STATUS_CHANGED: 'RESPONSE_SIM_STATUS_CHANGED',
    UNSOL_RESPONSE_CDMA_NEW_SMS: 'RESPONSE_CDMA_NEW_SMS',
    UNSOL_RESPONSE_NEW_BROADCAST_SMS: 'RESPONSE_NEW_BROADCAST_SMS',
    UNSOL_CDMA_RUIM_SMS_STORAGE_FULL: 'CDMA_RUIM_SMS_STORAGE_FULL',
    UNSOL_RESTRICTED_STATE_CHANGED: 'RESTRICTED_STATE_CHANGED',
    UNSOL_ENTER_EMERGENCY_CALLBACK_MODE: 'ENTER_EMERGENCY_CALLBACK_MODE',
    UNSOL_CDMA_CALL_WAITING: 'CDMA_CALL_WAITING',
    UNSOL_CDMA_OTA_PROVISION_STATUS: 'CDMA_OTA_PROVISION_STATUS',
    UNSOL_CDMA_INFO_REC: 'CDMA_INFO_REC',
    UNSOL_OEM_HOOK_RAW: 'OEM_HOOK_RAW',
    UNSOL_RINGBACK_TONE: 'RINGBACK_TONE',
    UNSOL_RESEND_INCALL_MUTE: 'RESEND_INCALL_MUTE',
    UNSOL_CDMA_SUBSCRIPTION_SOURCE_CHANGED: 'CDMA_SUBSCRIPTION_SOURCE_CHANGED',
    UNSOL_CDMA_PRL_CHANGED: 'CDMA_PRL_CHANGED',
    UNSOL_EXIT_EMERGENCY_CALLBACK_MODE: 'EXIT_EMERGENCY_CALLBACK_MODE',
    UNSOL_RIL_CONNECTED: 'RIL_CONNECTED',
    UNSOL_VOICE_RADIO_TECH_CHANGED: 'VOICE_RADIO_TECH_CHANGED',
    UNSOL_CELL_INFO_LIST: 'CELL_INFO_LIST',
    UNSOL_RESPONSE_IMS_NETWORK_STATE_CHANGED: 'RESPONSE_IMS_NETWORK_STATE_CHANGED',
    UNSOL_UICC_SUBSCRIPTION_STATUS_CHANGED: 'UICC_SUBSCRIPTION_STATUS_CHANGED',
    UNSOL_SRVCC_STATE_NOTIFY: 'SRVCC_STATE_NOTIFY',
    UNSOL_HARDWARE_CONFIG_CHANGED: 'HARDWARE_CONFIG_CHANGED',
    UNSOL_DC_RT_INFO_CHANGED: 'DC_RT_INFO_CHANGED',
    UNSOL_RADIO_CAPABILITY: 'RADIO_CAPABILITY',
    UNSOL_ON_SS: 'ON_SS',
    UNSOL_STK_CC_ALPHA_NOTIFY: 'STK_CC_ALPHA_NOTIFY',
    UNSOL_LCEDATA_RECV: 'LCEDATA_RECV',
    UNSOL_PCO_DATA: 'PCO_DATA'
}
# RESTRICTED_STATE
RESTRICTED_STATE_NONE = 0x0000
RESTRICTED_STATE_CS_EMERGENCY = 0x0001
RESTRICTED_STATE_CS_NORMAL = 0x0002
RESTRICTED_STATE_CS_ALL = 0x0004
RESTRICTED_STATE_PS_ALL = 0x0010
RESTRICTED_STATE = {
    RESTRICTED_STATE_NONE: 'NONE',
    RESTRICTED_STATE_CS_EMERGENCY: 'CS_EMERGENCY',
    RESTRICTED_STATE_CS_NORMAL: 'CS_NORMAL',
    RESTRICTED_STATE_CS_ALL: 'CS_ALL',
    RESTRICTED_STATE_PS_ALL: 'PS_ALL'
}
